pagopa/selfcare-onboarding-frontend

src/components/steps/StepOnboardingFormData.tsx, src/lib/__mocks__/mockApiRequests.ts
Enable checkOrganization Api call for all prod-fd products
After the prod-fd-garantito product was added it was requested to enable the api call for this product. Since this call is only neded for prod fideiussioni it was enbled for all products that start with "prod-fd".
Run locally with mocks and integration testing. Went to basepath/onboarding/prod-fd-garantito
=> SLEC-2897 Enable checkOrganization API call for all fideiussioni products

src/components/steps/StepOnboardingFormData.tsx, src/lib/__mocks__/mockApiRequests.ts
Enable checkOrganization API call for all Fideiussioni products
New product was added "prod-fd-garantito"
Test on dev
=> SLEC-2897 Enable checkOrganization API call fideiussioni products

src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx, src/views/onboarding/__tests__/Onboarding.test.tsx
- PA can search only the correct entities in the API search parties
- Aoo/uoo search is now enabled to search by correct categories
- Search by businessName is filtered for PA entities (the different institutionType are not shown
This implementation permit to not show institutionType different from PA in the search
Feature tested in DEV environment
=> SELC-3029 PA can search only the correct entities in the API search parties

.env.development.local, src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx, src/components/onboardingFormData/PersonalAndBillingDataSection.tsx, src/lib/__mocks__/mockApiRequests.ts, src/utils/constants.ts, src/views/onboarding/Onboarding.tsx
- Added API call for retrieve insuranceCompany from taxId
- Prefilled field in billingData step
- Adapted the submit in order to send IvassCode if present
In order to allow the organization to also search via tax code, ensure that the IvassCode field is pre-populated in the next form and that the information is then sent via submit once adhesion is concluded
Local and aiming envinroment DEV data
=> [SELC-3221] feat: Added API call for retrieve insuranceCompany from taxId + prefilled field in billingData step + adapted the submit

src/components/steps/StepOnboardingData.tsx, src/lib/__mocks__/mockApiRequests.ts, src/views/onboarding/Onboarding.tsx, src/views/onboarding/__tests__/Onboarding.test.tsx
When makeing get onboarding api call send taxCode_Aoo/uocode as externalId in params 
If the central institution was onboarded it would find it by taxId and return 200. Need to send aoo/uo code as well if we want to know if the aoo is onbarded.
Unit tests and by movked uat enviroment.
=> [SELC-3239] fix:  send taxCode + aoo/uo code to getOboarding api parms

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx, src/components/steps/StepOnboardingFormData.tsx, src/lib/__mocks__/mockApiRequests.ts, src/locale/it.ts, src/model/Country.ts, src/model/GeographicTaxonomies.ts
Called geotaxonomy API in order to retrieve countries, created a map with what is needed and kept only the municipalities
To populate the Autocomplete component with the cities, the Geotaxonomies API call was invoked where only the municipalities were kept and the description was cleaned by removing "- MUNICIPALITY".
Aiming dev environment, the search works and the selection is saved.
=> [SELC-3336] feat: Called geotaxonomy API in order to retrieve countries, created a map with what is needed and kept only the municipalities

src/views/onboarding/Onboarding.tsx, src/views/onboarding/__tests__/Onboarding.test.tsx
InstitutionLocationData will not be sent in case of non-existence
For institutions not present in IPA and for institutions not present on the IPA and not belonging to the PAs, it is necessary not to send the object (previously it was sent in the payload anyway and being empty, it was translated as an object with its keys set to null)
Test in DEV environment, now for institution not present on the IPA and not PA, in the submit payload the institutionLocation data will not be sent
=> [SELC-3338] fix: InstitutionLocationData will not be sent in case of non-existence

src/components/steps/StepOnboardingFormData.tsx, src/lib/__mocks__/mockApiRequests.ts, src/views/onboarding/Onboarding.tsx, src/views/onboarding/components/OnboardingStep1_5.tsx
Used taxCode instead of externalInstitutionId
In order to resolve the error of API call for institution that not have certificated data: because in the case of an institution not selected from the list, the data used previously (externalInstitutionId) will be undefined. For linearity, it has also been replaced in the other calls. Also removed an unnecessary condition constraint.
Aiming DEV environment data, the API call responds as expected: 
- 400 or 404 in the case of a non-onboarded institution
- 204 in the case of an already onboarded institution
=> [SELC-3292] fix: Used taxCode instead of externalInstitutionId

src/components/steps/StepOnboardingFormData.tsx
Fixed formik validation for origin different from ipa
The bug consisted in the fact that for institutionTypes other than PA but with origin coming from IPA, the validation of the completeness of the form was not successful and the continua remained disabled. A missing check has been added to make this happen.
Aiming DEV environment, the validation of the form with data institution for institutionTypes other than PA but with origin coming from IPA goes success and confirm button is enabled, then an onboarding has been tested and is successful, with the expected payload
=> [SELC-3335] fix: Fixed formik validation for origin different from ipa

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx, src/components/steps/StepOnboardingFormData.tsx, src/lib/__mocks__/mockApiRequests.ts, src/utils/constants.ts, src/utils/formatting-utils.ts, src/views/onboarding/__tests__/Onboarding.test.tsx, types.ts
* SELC-3362 city and county fields visible for institutions from IPA.
Integrated new api that takes istat code as param and return location data  
During onboarding for institutions with origin IPA the fields city should be prefilled and be read only.
=> [SELC-3362] feat: Show fields city and province precompiled and disabled

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
Hide cities options from autocomplete dropdown when no value selected
Tested in local enviroment.
=> Fix: hide cities options from autocomplete dropdown

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx, src/views/onboarding/__tests__/Onboarding.test.tsx
Read the fields city and county from the AOO / UO not from the central institution.
Call proxy registry with istat code of aoo / uo.
During onboarding with aoo or uo the city and county fields would be filled with the value of the central institution 
Integration testing from local and unit test
=> [SELC-3402] fix city and county fields for UO/AOO

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx, src/views/onboarding/__tests__/Onboarding.test.tsx
Read the fields city and county from the AOO / UO not from the central institution.  
Call proxy registry with istat code of aoo / uo.
During onboarding with aoo or uo the city and county fields would be filled with the value of the central institution
Integration testing from local and unit test
=> [SELC-3402] fix: city and county fields for UO/AOO

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx, src/components/steps/StepOnboardingFormData.tsx, src/lib/__mocks__/mockApiRequests.ts, src/views/onboarding/__tests__/Onboarding.test.tsx, types.ts
Retrieved Istatcode in premium flow in order to be able to obtain city, country, county
In order to be able to obtain city, country, county for the estabilished conditions also in premium onboarding flow and then, pre-fill the city and county fields
Tested aiming DEV data, the fields are prefilled for public administrations parties, also adapted mocks and make the logic work also in local environment
=> [SELC-3393] feat: Retrieved Istatcode in premium flow in order to be able to obtain city, country, county

src/components/steps/StepOnboardingFormData.tsx
Enabled continue button when form is prefilled in premium adhesion flow
In order to not have a disabled button when form is valid
Local execution
=> fix: Enabled continue button when form is prefilled in premium adhesion flow

src/components/steps/StepOnboardingFormData.tsx
Enabled continue button when form is prefilled in premium onboarding flow
In order to not have a disabled button when form is valid
Local execution
=> fix: Enabled continue button when form is prefilled in premium onboarding flow

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx, src/components/steps/StepOnboardingData.tsx, src/components/steps/StepOnboardingFormData.tsx, src/lib/__mocks__/mockApiRequests.ts, src/model/InstitutionLocationData.ts, src/views/OnBoardingSubProduct/OnBoardingSubProduct.tsx, types.ts
In the premium flow, to retrieve the institution data and prepopulate the fields, the onboarded-institution-info API call is available to read the data from.
Removed call to geoTax by istatCode.
For public administrations, the fields city, county, country are have been added in onboarded-institution-info API call.
=> [SELC-3496] fix: Handle fields city county for premium flow

src/components/BodyLogger.tsx
Added mixpanel event for open operative manual
In order to make analytics with opening operative manual, the event contains the from property which will be valorised with the point of the application from which the manual is accessed (onboarding/login/dashboard)
Local
=> [SELC-3585] feat: Added mixpanel event for open operative manual

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx, src/components/steps/StepOnboardingFormData.tsx, src/model/BillingData.ts, src/model/OnboardingFormData.ts, src/views/onboarding/Onboarding.tsx
RecipientCode is not required during onboarding on prod-interop for all institution types.
Prod-interop does not need recipient code beacuse its not an invoicable product.
=> [SELC-3501] feat: Hide Recipient code field for prod-interop

src/components/steps/StepOnboardingFormData.tsx, src/locale/it.ts
Block onboarding flow on prod-fd in case of generic error from verify vat number.
During onboarding on prod-fd if the API that verifies that the institution with a specific vat number was already registered returned an error code diffrent from 404 it would still allow to continue with the onboarding flow.
Tested by aiming at dev env.
=> [SELC-3747] feat: handle 404 error in for prod-fd verifyVatNumber API

src/components/steps/StepOnboardingFormData.tsx, src/model/AdditionalInformations.ts, src/views/onboarding/Onboarding.tsx, src/views/onboarding/components/OnBoardingProductStepDelegates.tsx, src/views/onboarding/components/StepAdditionalInformations.tsx
Sending the new additionalInformations object in the submit payload
In order to persist the new collected additionalInformations for GSP that going to do an adhesion for prod-pagopa
Tested in local aiming dev environment, the submit goes in 201 statusCode correctly and the payload is in
=> [SELC-3794] feat: Sending the new additionalInformations object in the submit payload

src/components/steps/StepOnboardingFormData.tsx, src/locale/it.ts, src/model/AdditionalInformations.ts, src/views/onboarding/Onboarding.tsx, src/views/onboarding/components/OnBoardingProductStepDelegates.tsx, src/views/onboarding/components/StepAdditionalInformations.tsx
Sending the new additionalInformations object in the submit payload
Block onboarding for prod-fd in case of error difrent from 404 during verification of vat number.
In order to persist the new collected additionalInformations for GSP that going to do an adhesion for prod-pagopa
In order not to allow onboarding of an institution that has not been verified yet the vat number
Tested in local by aiming to dev data.
=> [SELC-3794-3747] feat:vSending additionalInformation object in the submit & handle general errors for verifyVatNumber

src/views/onboarding/components/StepAdditionalInformations.tsx
Empty the TextField when unchecking the "other" checkbox and improvements in code logic
Improvements of the user experience and, with this implementation, we don't risk to send other information string also when user uncheck "other" checkbox
Tested in local environment, after the checkbox is unchecked, the input is removed
=> [SELC-3919] feat: Empty the TextField when unchecking the "other" checkbox and improvements in code logic

src/utils/constants.ts, src/views/OnBoardingSubProduct/OnBoardingSubProduct.tsx, src/views/OnBoardingSubProduct/components/subProductStepPricingPlan/SubProductStepSelectPricingPlan.tsx, src/views/onboarding/components/StepAdditionalInformations.tsx
- Empty the TextField when unchecking the "other" checkbox and improvements in code logic
- V2 version basePath only for DEV environment
- Check on available pricingPlanId based on rest api response
For resolve the previous static approach that expect as correct pricingPlanId only those indicated by the condition. With this implementation is used a dynamic approach also for validation of correct pricingPlanId and other implementation used to aiming new v2 basePath REST API temporary only for DEV enviroment
All features of this pullrequest has been tested on DEV environment
=> [SELC-3919] feat: Empty the TextField when unchecking the "other" checkbox and improvements in code logic + other features

src/views/onboarding/Onboarding.tsx, src/views/onboarding/components/OnBoardingProductStepDelegates.tsx
hide modal for PT until copy is changed. 
Institutions of type PT are not required to sign the contract so the modal should be hidden at the moment for PT until new copy.
Tested locally
=> [SELC-4025] fix: hide modal of confimation of onboarding for PT

src/components/autocomplete/Autocomplete.tsx, src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx, src/components/autocomplete/components/asyncAutocomplete/components/AsyncAutocompleteSearch.tsx, src/components/steps/StepSearchParty.tsx, src/locale/it.ts, src/views/onboarding/Onboarding.tsx
Forwarding is permitted without selecting only for GPS
The search for GPS from the IPA database has also been included for the GPS belonging to the app-io and prod-pagopa products. A banner has been added to allow the search step to be skipped. When the search fails, the continue button will be enabled.
Tested in DEV ensuring all the cases and logic are covered. Tested, also, with a E2E, submitting correctly an onboarding request and, then approve it in admin overview
=> [SELC-3767] feat: forwarding is permitted without selecting only for GPS

src/components/onboardingFormData/ErrorPIVAModal.tsx, src/components/steps/StepOnboardingFormData.tsx, src/locale/it.ts
In  the onboarding flow to prod-fd add a modal in case of generic error from BE during verification of vat number.. 
For techincal problems with the product fiddeiussioni the BE returns status code 500. Add modal that allows redirct to select institutions in dashboard. 
Tested locally
=> [SELC-3966] Feat: Modal for handling generic errror vat number verification

src/components/RadioWithTextField.tsx
change max lentgth if input field ipa code to 16.
During onboarding of gsp into prod-pagopa if the gsp is from ipa its required to compile ipa code input field. IPA code can be longer than the previus limit of 6 charachters
Tested locally
=> [SELC-4263] Feat: change maxlength of IPA code input to 16

src/components/steps/StepOnboardingFormData.tsx
Comment api verifyVatNumber
In order to allow testing for prod-fd since verifyVatNumber always gives error atm
=> Disable api call of verify vat number in order to allow testing for prod-fd

.env.development.local, src/components/onboardingFormData/PersonalAndBillingDataSection.tsx, src/components/steps/StepOnboardingData.tsx, src/lib/__mocks__/mockApiRequests.ts, src/utils/constants.ts, src/views/OnBoardingSubProduct/OnBoardingSubProduct.tsx, src/views/onboarding/__tests__/Onboarding.test.tsx
Substitute deprecated api /onboarded-institution-info with /onboarding?taxCode&productId
To have the fields city and county prefilled a new api was called only for the sub product onboarding flow.
Tested locally by aiming at dev data
=> [SELC-4481] Feat: substitute deprecated api call instituion-info

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx, src/components/steps/StepOnboardingFormData.tsx
Hide PivaEquals checkbox when party not have piva
In order to not show this checkbox that is useless for this use case (party not have vatNumber
Tested in local environment, the behaviour is the expected
=> feat: Hide VatNumberEqualsFiscalCode checkbox when party not have vatnumber

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx, src/components/steps/StepOnboardingFormData.tsx
[SELC-4752] feat: Removed "party not have vatNumber" for fideiussioni and fideiussioni garantito products
The adhesions for product fideiussioni and fideiussioni garantito expected vatNumber as mandatory data
Tested in local environment, for this two product the feature is not available
[SELC-4752]: https://pagopa.atlassian.net/browse/SELC-4752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-4752] feat: Removed "party not have vatNumber" for fideiussioni and fideiussioni garantito products

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx, src/lib/__mocks__/mockApiRequests.ts
[SELC-4742] fix: equals2vatNumber checkbox issue
Resolved an issue related to equal2vatNumber checkbox that was not showed when taxCode is not defined
Tested in local environment, all cases are cover as expected
[SELC-4742]: https://pagopa.atlassian.net/browse/SELC-4742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-4742] fix: equals2vatNumber checkbox issue

src/components/__tests__/StepSearchParty.test.tsx, src/components/steps/StepSearchParty.tsx
[SELC-4582] feat: Mandatory IPA source selection for app-io e app-io-sign products public services manager
For public services managers that onboard for this two products is not available the onboarding without IPA source
Tested in local environment, the public services managers will not able to onboard for app-io or app-io-sign without select the party from the list provided from ipa source. Added unit tests too.
[SELC-4582]: https://pagopa.atlassian.net/browse/SELC-4582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-4582] feat: Mandatory IPA source selection for app-io e app-io-sign products public services managers

src/components/__tests__/StepSearchParty.test.tsx, src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx, src/components/steps/StepSearchParty.tsx, src/utils/constants.ts
[SELC-4582] fix: No auto-enabled button for mandatory ipa products for public service managers + added strong unitTests
Fixed auto-enabled button for mandatory ipa products for public service managers and added strong unitTests
Tested in local environment, dev environment with behaviour tests and with unitTests that cover all the cases required
[SELC-4582]: https://pagopa.atlassian.net/browse/SELC-4582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-4582] fix: No auto-enabled button for mandatory ipa products for public service managers + added strong unitTests

src/views/onboarding/Onboarding.tsx, src/views/onboarding/__tests__/Onboarding.test.tsx
[SELC-5040] feat: originId is always filled when available
The information is no longer valid in the microservice for entities coming from ipa, so it must be sent to the REST submit
Tested in local environment, the originId is always filled when available
[SELC-5040]: https://pagopa.atlassian.net/browse/SELC-5040?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-5040] feat: originId is always filled when available

src/components/ConfirmRegistrationStep0.tsx, src/components/PlatformUserForm.tsx, src/components/steps/StepAddManager.tsx, src/components/steps/StepOnboardingData.tsx, src/locale/it.ts, src/views/OnBoardingSubProduct/OnBoardingSubProduct.tsx, src/views/UserNotAllowedPage.tsx, src/views/onboarding/Onboarding.tsx, src/views/onboarding/__tests__/Onboarding.test.tsx, src/views/onboarding/components/OnBoardingProductStepDelegates.tsx, src/views/onboarding/components/StepVerifyOnboarding.tsx
[SELC-4373] feat: Allowed same taxcode and email with different role for add new user flow
In order to allow the legal representative to be an administrator only for the new user addition flow. The user cannot be admin twice
Tested in local environment with behaviour tests and unit tests, the legal representative can be an administrator only for the new user addition flow and can't be admin twice
[SELC-4373]: https://pagopa.atlassian.net/browse/SELC-4373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-4373] feat: Allowed same taxcode and email with different role for add new user flow

package.json, src/components/ConfirmRegistrationStep0.tsx, src/components/PlatformUserForm.tsx, src/components/RolesInformations.tsx, src/components/steps/StepAddManager.tsx, src/components/steps/StepOnboardingData.tsx, src/locale/it.ts, src/views/OnBoardingSubProduct/OnBoardingSubProduct.tsx, src/views/UserNotAllowedPage.tsx, src/views/onboarding/Onboarding.tsx, src/views/onboarding/__tests__/Onboarding.test.tsx, src/views/onboarding/components/OnBoardingProductStepDelegates.tsx, src/views/onboarding/components/OnboardingStep1_5.tsx, src/views/onboarding/components/StepVerifyOnboarding.tsx, yarn.lock
[SELC-4372] feat: Added the addNewAdmin entrypoint link in the alreadyOnboarded page
[SELC-4373] feat: Allowed same taxcode and email with different role for add new user flow
In order to allow the user to add as an admin of the already onboarded party. The legal representative to be an administrator only for the new user addition flow. The user cannot be admin twice
Tested in dev environment with behaviour tests, the legal representative can be an administrator only for the new user addition flow and can't be admin twice. Also added unit tests.
[SELC-4373]: https://pagopa.atlassian.net/browse/SELC-4373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SELC-4372]: https://pagopa.atlassian.net/browse/SELC-4372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …
=> SELC-4372 SELC-4373

src/lib/__mocks__/mockApiRequests.ts, src/utils/constants.ts, src/views/onboardingRequest/cancel/__tests__/CancelRequestComponent.test.tsx, src/views/onboardingUser/OnboardingUser.tsx, src/views/onboardingUser/__tests__/OnboardingUser.test.tsx, src/views/onboardingUser/components/StepSelectProduct.tsx, types.ts
[SELC-5208] feat: Replaced getProducts with getProductsAdmin + removed product filtering
Invoked the new REST dedicated only for the add user flow in order to retrieve only the products allowed to add new user instead of all products
Tested in dev environment, the API give only the products expected.
[SELC-5208]: https://pagopa.atlassian.net/browse/SELC-5208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-5208] feat: Replaced getProducts with getProductsAdmin + removed product filtering

src/components/__tests__/StepSearchParty.test.tsx, src/components/steps/StepSearchParty.tsx, src/locale/it.ts
[SELC-5202] feat: Added isAggregator checkbox only for PA institution types + unit test
Manage aggregator onboardings, added this checkbox that allow the party to self declare as aggregator
Tested in local environment with unit test and executing the client, the checkbox appears only for PA for all products as expected
[SELC-5202]: https://pagopa.atlassian.net/browse/SELC-5202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-5202] feat: Added isAggregator checkbox only for PA institution types + unit test

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx, src/components/onboardingFormData/__tests__/PersonalAndBillingDataSection.test.tsx, src/locale/it.ts
Added text "(facoltativo)" in the email address field label for all products except for "Firma con IO"
For the Product "Firma con IO" the email address field is required, for all the other product it's not
local env
=> [SELC-5209] feat: Added "(facoltativo)" in the email address field for all products except "Firma con IO"

src/components/steps/StepSearchParty.tsx, src/lib/__mocks__/mockApiRequests.ts, src/locale/it.ts, src/model/OnboardedParty.ts, src/model/OnboardingFormData.ts, src/utils/selected2OnboardingData.ts, src/views/onboardingProduct/OnboardingProduct.tsx
[SELC-5203] feat: Added modal before forward when party is an aggregator
In order to notify the party that is self-declaring itself as an aggregator before proceeding
Tested in local environment, the popup appears correctly only when the aggregator checkbox is checked
[SELC-5203]: https://pagopa.atlassian.net/browse/SELC-5203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-5203] feat: Added modal before forward when party is an aggregator

src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx, src/components/autocomplete/components/asyncAutocomplete/components/AsyncAutocompleteResultsCode.tsx, src/components/autocomplete/components/asyncAutocomplete/components/AsyncAutocompleteSearch.tsx, src/utils/constants.ts, src/views/onboardingPremium/components/SubProductStepVerifyInputs.tsx, src/views/onboardingProduct/OnboardingProduct.tsx
[SELC-5240] feat: originId filled with subunitCode + added partyLogo and parentDescription in the selected party if present
In order to provide the originId as the subunitCode instead of the ipa code of EC and develop some improvements
Tested in dev environment, the parentDescription and the partyLogo are showed if present (in the case of partyLogo, if not present a custom logo, the default logo is showed). Done some onboarding and, now, the originId is enhanced with the subunit code in the case of AOO or UO onboarding
[SELC-5240]: https://pagopa.atlassian.net/browse/SELC-5240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-5240] feat: originId filled with subunitCode + added partyLogo and parentDescription in the selected party if present

src/components/__tests__/StepInstitutionType.test.tsx, src/utils/constants.ts
[SELC-5172] feat: Allow to access to "Società a controllo pubblico" for interoperability
Allow to access to "Società a controllo pubblico" for interoperability product
Checked if the "Società a controllo pubblico" choice is prensent  in first step page
[SELC-5172]: https://pagopa.atlassian.net/browse/SELC-5172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-5172] feat: Allow to access to "Società a controllo pubblico" for interoperability

src/components/__tests__/StepSearchParty.test.tsx, src/components/steps/StepSearchParty.tsx, src/model/AggregateInstitution.ts, src/views/onboardingProduct/OnboardingProduct.tsx, src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx, src/views/onboardingProduct/components/StepUploadAggregates.tsx
feat: Aggregates feature available only for prod-io + added aggregates list on submit
Persist the aggregates list by pass the list on the onboarding product submit rest api + party self declare as aggregator available only for App IO product.
Tested in dev environment, the list of aggregates and the boolean too are passed correctly if present (in case of party different from PA institutionType and that try to onboard a product different to prod-io, the information are not passed).
=> feat: Aggregates feature available only for prod-io + added aggregates list on submit

src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx, src/components/autocomplete/components/asyncAutocomplete/components/AsyncAutocompleteResultsCode.tsx, src/components/autocomplete/components/asyncAutocomplete/components/AsyncAutocompleteSearch.tsx, src/components/autocomplete/components/partyAdvancedSearchType/PartyAdvancedSelect.tsx, src/components/steps/StepSearchParty.tsx, src/lib/__mocks__/mockApiRequests.ts, src/locale/it.ts, src/utils/constants.ts, src/views/onboardingProduct/OnboardingProduct.tsx
[SELC-5173] feat: API invocation for private body search via CF
As a user of an organization who wants to subscribe to a product, I want to be able to select my organization by searching for it by tax code on the Infocamere data source
tested if inserting a taxCode the API on the infocamere data source retrives the wanted data
[SELC-5173]: https://pagopa.atlassian.net/browse/SELC-5173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-5173] feat: API invocation for private body search via CF

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx, src/components/onboardingFormData/__tests__/PersonalAndBillingDataSection.test.tsx, src/components/steps/StepOnboardingFormData.tsx, src/lib/__mocks__/mockApiRequests.ts, src/utils/validateFields.ts, src/views/onboardingPremium/__tests__/OnboardingPremium.test.tsx, src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx
[SELC-5314] feat: SFE Billing Code field validation
the field for sfe has to be free and be validated calling the API verifyTaxCodeInvoicing
Tested if when landing in page the field SFE is free and editable.
Tested if at the change of the value SFE field the API verifyTaxCodeInvoicing has been called with the correct values and that has been retrived the correct response.
[SELC-5314]: https://pagopa.atlassian.net/browse/SELC-5314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-5314] feat: SFE Billing Code field validation

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
[SELC-5344] feat: Show the "Codice Fiscale SFE" field under the "Codice univoco o SDI" field.
Show the "Codice Fiscale SFE" field under the "Codice univoco o SDI" field.
Tested that  when a valid sdiCode it's inserted in the sdiCode field, the sfeCode field is shown under the sdiCode field
[SELC-5344]: https://pagopa.atlassian.net/browse/SELC-5344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-5344] feat: Show the "Codice Fiscale SFE" field under the "Codice univoco o SDI" field.

src/views/onboardingUser/OnboardingUser.tsx
…niqueCode nor aooUniqueCode
[SELC-4567] fix: avoid to send subunitCode if not present nor the uoUniqueCode nor the aooUniqueCode
Avoid to send subunitCode  if not present nor the uoUniqueCode nor the aooUniqueCode, in the request of the API ONBOARDING_NEW_USER
Tested that if the uoUniqueCode and the aooUniqueCode are not present, the request ONBOARDING_NEW_USER goes succesful and the request for a new user is send.
[SELC-4567]: https://pagopa.atlassian.net/browse/SELC-4567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-4567] fix: avoid to send subunitCode if not present

src/views/onboardingProduct/OnboardingProduct.tsx
[SELC-5478] fix: Manually joining a GPS
When the user click the link "Inserisci manualmente i dati del tuo ente" there is an API invocation that controls if the party were already onboarded, passing as parameter the party taxcode, but in that specific case the taxcode will never exist.
Tested that when the user click the link "Inserisci manualmente i dati del tuo ente" it brings him in the correct step
[SELC-5478]: https://pagopa.atlassian.net/browse/SELC-5478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-5478] fix: Manually joining a GPS

src/components/steps/StepSearchParty.tsx, src/utils/selected2OnboardingData.ts, src/views/onboardingProduct/OnboardingProduct.tsx, src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx
[SELC-5496] feat: Updated originId for onboarding flow of SCP and PRV
In the onboarding request flow of SCP and PRV the of institution types of SCP and PRV makes their request to the infocamere resocurces, and they needed a different value type for the fields originId and origin.
Tested that in the onboarding request flow of SCP and PRV the field origin and originId have the correct value and that the request goes succesful, and updated and added junit tests.
[SELC-5496]: https://pagopa.atlassian.net/browse/SELC-5496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-5496] feat: Updated originId for onboarding flow of SCP and PRV

src/components/__tests__/StepInstitutionType.test.tsx, src/locale/it.ts, src/utils/constants.ts
[SELC-5491] feat: Added RadioButton "Altro" for Private Entities
With the new radioButton "Altro" now the users can access to a new onboarding flow for the Private Entities for the product "Piattaforma pagoPA"
Tested that in the selection page of the institution type there is the new radioButton "Altro".
Tested with unit test.
[SELC-5491]: https://pagopa.atlassian.net/browse/SELC-5491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-5491] feat: Added RadioButton "Altro" for Private Entities

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx, src/components/steps/StepOnboardingFormData.tsx, src/components/steps/StepSearchParty.tsx, src/locale/it.ts, src/utils/selected2OnboardingData.ts, src/utils/validateFields.ts, src/views/onboardingProduct/OnboardingProduct.tsx, src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx
[SELC-5492] feat: Connection with empty data entry form
When the user choice the institutionType "Altro" in first step is redirect directly to the form billing data skipping the step search party. when it land in the step billing data it will be all empty and with the data to be setted.
Tested that the onboarding flow for the institution type "Altro" works and send the data as expected.
Tested with unit test.
[SELC-5492]: https://pagopa.atlassian.net/browse/SELC-5492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-5492] feat: Connection with empty data entry form

src/components/onboardingFormData/taxonomy/GeoTaxonomySection.tsx
… value is pre-set
[SELC-5597] feat: GeoTaxonomySection does not set province when local value is pre-set
GeoTaxonomySection does not set province when local value is pre-set
Tested that in the GeoTaxonomySection, when the local value is pre-set, there is also the value of the province
[SELC-5597]: https://pagopa.atlassian.net/browse/SELC-5597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-5597] feat: GeoTaxonomySection does not set province when local value is pre-set

src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx, src/lib/__mocks__/mockApiRequests.ts, src/utils/constants.ts, src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx
[SELC-5580] feat: read the category filter exposed on the cdn
the categories has been exposed on the storage of the cdn and to read them we have to make a call for retrive those informations
Tested that those information are retrived
[SELC-5580]: https://pagopa.atlassian.net/browse/SELC-5580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-5580] feat: read the category filter exposed on the cdn

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
[SELC-5704] fix: fixed the "P.IVA" checkbox when the CF value has not yet been set
the "P.IVA" checkbox when the CF value wasn't setted yet, it was already checked.
Tested that when the CF value it's not setted yest, the checkbox it's not checked. When the cf value is entered, the checkbox it's enabled and clickable
[SELC-5704]: https://pagopa.atlassian.net/browse/SELC-5704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-5704] fix: fixed the "P.IVA" checkbox when the CF value has not yet been set

src/components/BodyLogger.tsx
[SELC-6027] feat: View and path incorrect for procut prod-io-premium
redirect to corret premium path of prod-io product if is typed in the subProductId without the productId before
Tested that if typed in the research bar of the browser the incorrect path "onboarding/prod-io-premium" it'll be redirect directly to the correct one "onboarding/prod-io/prod-io-premium"
[SELC-6027]: https://pagopa.atlassian.net/browse/SELC-6027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-6027] feat: View and path incorrect for procut prod-io-premium

src/locale/it.ts, src/model/AdditionalGpuInformations.ts, src/views/onboardingProduct/OnboardingProduct.tsx, src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx, src/views/onboardingProduct/components/StepAdditionalGpuInformations.tsx
[SELC-6168] Feat: added longTermPayments boolean field in the onboarding request
New longTermPayments boolean field in the onboarding request  gpuData object for additionalGpuInformation. this feature is required for the onboarding flow of a GPU
Tested that the new field longTermPayments it's send in the onboarding request of a GPU
[SELC-6168]: https://pagopa.atlassian.net/browse/SELC-6168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-6168] Feat: added longTermPayments boolean field in the onboarding request

src/views/onboardingPremium/OnboardingPremium.tsx, src/views/onboardingPremium/__tests__/OnboardingPremium.test.tsx, src/views/onboardingPremium/components/SubProductStepVerifyInputs.tsx
Feat: Updated io-premium flow
Updated ONBOARDING_GET_USER_PARTIES Api call in the first step of Premium onboarding flow. now the API with the filter  productId is called just one time and no more for both product father and son, but just for the son with the subProductId.
=> Feat: Updated io-premium flow

src/views/onboardingPremium/components/SubProductStepSubmit.tsx, src/views/onboardingPremium/components/SubProductSubmitFetch.ts
[SELC-6800] Feat: fixed the page of conflict error for the pagoPA insights flow
In the pagoPA insights membership flow, the error "your institution has already joined" returns in the case of 409
[SELC-6800]: https://pagopa.atlassian.net/browse/SELC-6800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-6800] Feat: fixed the page of conflict error for the pagoPA insights flow

src/components/steps/StepAddManager.tsx, src/utils/api/userValidate.ts, src/utils/test-utils.tsx, src/views/onboardingProduct/components/StepAddAdmin.tsx
Fixed the user validation process in the steps of AddManager and AddAdmin
In the user validation process, for the AddManager and AddAdmin phases, there is an API that checks the validation of the user, who is called Manager or Delegate. If the user is not present in the PDV services, BFF creates the user who can later be indicated as Manager or Delegate for other onboardings. The FE was blocking the process because when the user check is invoked and the user is not found in the PDV services, the API returns the 404 "not found" error and the FE was showing a blocking error.
=> Fixed the user validation process in the steps of AddManager and AddAdmin

src/locale/it.ts, src/views/onboardingPremium/OnboardingPremium.tsx, src/views/onboardingPremium/components/SubProductStepNoParties.tsx
[SELC-6587] Feat: Edit "Select your institution" page if there is an empty list for child products
In case a user accesses the membership flow of a child product (prod-io-premium, prod-dashboard-psp) via an external link, if the user has no associated entities (the entity has not joined IO, the entity has already joined the child product or the user does not have a role on the product), we currently show the empty list with “no results”.
[SELC-6587]: https://pagopa.atlassian.net/browse/SELC-6587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-6587] Feat: Edit "Select your institution" page if there is an empty list for child products

src/components/steps/StepOnboardingFormData.tsx, src/model/OnboardingFormData.ts, src/utils/test-utils.tsx, src/views/onboardingProduct/OnboardingProduct.tsx, src/views/onboardingProduct/components/StepVerifyOnboarding.tsx
[SELC-7768] Feat: delete soleTrader field
The soleTrader field is obsolete and its utility will be replaced with the new institutionType PRV_PF for the PARI product onboarding flow searched with the personalTaxCode
[SELC-7768]: https://pagopa.atlassian.net/browse/SELC-7768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SELC-7768] Feat: delete soleTrader field
