pagopa/selfcare-onboarding-frontend

src/components/OnboardingStep1.tsx
src/components/OnboardingStep1_5.tsx
src/components/StyledIntro.tsx
src/lib/constants.ts
src/views/Onboarding.tsx
types.ts

checking onboarding status after party selection

already onboarded institution

---

.env
src/components/AsyncAutocomplete.tsx
src/react-app-env.d.ts

max 50 institutions fetched as default

SELC-95 max 50 institutions fetched as default

---

src/components/OnboardingStep1.tsx

https://www.figma.com/file/TDNVa5OJXdasNwyFPufnzR/Self-Care_MVP?node-id=433%3A7605
https://www.figma.com/file/TDNVa5OJXdasNwyFPufnzR/Self-Care_MVP?node-id=433%3A7605

labels update

---

src/views/onboarding/components/OnBoardingProductStepDelegates.tsx

Co-authored-by: loremedda <lorenzo.medda.sa@nttdata.com>

SELC-1288 Onboarding - 409 (conflitto nei dati inseriti): al click su "Sono io l'Amministratore" continuo a vedere i messaggi d'errore

---

src/lib/__mocks__/mockApiRequests.ts
src/locale/it.ts
src/views/onboarding/Onboarding.tsx

Co-authored-by: loremedda <lorenzo.medda.sa@nttdata.com>

SELC-1358 Handling 403 when submitting onboarding request

---

.devops/deploy-pipelines.yml

Co-authored-by: anttorre <antonio.torre@everis.com>

SELC-1392 enabling assistance in PROD (#163)

---

src/views/onboarding/Onboarding.tsx

SELC-1363 - removed duplicate message

Selc 1363 remove duplicate message (#174)

---

src/components/ConfirmRegistrationStep1.tsx
src/locale/it.ts

SELC-1439 Firma P7M: esplicitazione in pagina caricamento Accordo sia base che Premium

---

src/components/ConfirmRegistrationStep1.tsx
src/locale/it.ts

correct text in adhesion error popup

---

src/components/ConfirmRegistrationStep1.tsx
src/locale/it.ts

changes in text

---

src/views/OnBoardingSubProduct/components/SubProductStepSelectUserParty.tsx

Removing 'selection effect' and hover when user have only one party

SELC-1510 Onboarding Premium - unico ente collegato: rimozione effetto UI selezione

---

src/views/OnBoardingSubProduct/components/SubProductStepSelectUserParty.tsx

SELC-1510 Removing 'selection effect' and hover when user have only one party

---

package.json
src/components/PlatformUserForm.tsx
src/hooks/useLogin.ts
src/lib/__mocks__/mockApiRequests.ts
src/views/OnBoardingSubProduct/__tests__/OnboardingSubProduct.test.tsx
src/views/onboarding/__tests__/Onboarding.test.tsx
yarn.lock

…e 6 lettere del codice fiscale
* temp commit
* SELC-1509 Check su CF: coincidenza fra Nome e Cognome inseriti e prime 6 lettere del codice fiscale
* temp commit
* SELC-1509 optimization in code
* SELC-1509 implementation check cf for onboarding forms + fix little bug and fix UnitTests

SELC-1509 Check su CF: coincidenza fra Nome e Cognome inseriti e prime 6 lettere del codice fiscale

---

src/components/steps/StepBillingData.tsx
src/components/steps/StepInstitutionType.tsx
src/components/steps/StepSearchParty.tsx
src/views/onboarding/Onboarding.tsx
src/views/onboarding/__tests__/Onboarding.test.tsx

* SELC-1532 - modified back action in stepBillingData if user comes frome dashboard
* Revert "SELC-1532 - moved step institution type (#223)"
This reverts commit
da23dc272d50856340e6b1e71952a8f94ebf3bc1 ac460586da1d6f8d3385928cf4167c7bb58993ec.

SELC-1532 - back button inbilling data

---

src/components/steps/StepAddManager.tsx
src/lib/__mocks__/mockApiRequests.ts
src/utils/api/userValidate.ts
src/views/OnBoardingSubProduct/OnBoardingSubProduct.tsx
src/views/onboarding/Onboarding.tsx
src/views/onboarding/components/OnBoardingProductStepDelegates.tsx

* SELC-1556 Post legal review changes in mixPanel Events+using correct taxCodes for generic and conflict cases
* SELC-1556 Correct generic errors event content

SELC-1556 Aggiunta e rimozione di attributi in eventi MixPanel post review legals

---

src/components/steps/StepInstitutionType.tsx
src/locale/it.ts
src/views/onboarding/Onboarding.tsx

SELC-1561-different InstitutionType displayed according to the selectedProduct

SELC-1561-institution-type

---

package.json
yarn.lock

SELC-1589 Managment of aphostrophe, in order to not consider it as a consonant in taxCode match

---

src/views/onboarding/Onboarding.tsx

Resolved partyId not valorise also when having externalId data in flow started from dashboard

---

package.json
yarn.lock

SELC-1589 Management of multiple apostrophes too

---

src/locale/it.ts
src/views/CompleteRegistrationComponent.tsx
src/views/JwtInvalidPage.tsx

Added also some improvements to code

SELC-1583 Tracciare casistiche eventi di errore durante la validazione del token di onboarding

---

src/services/tokenServices.ts
src/views/ConfirmCancellationPage.tsx
src/views/RejectRegistration.tsx

* Fixed mixpanel events with new modifies
* temp commit
* temp commit
* Commit with review modifies

Fixed mixpanel events with new modifies

---

src/components/steps/StepBillingData.tsx
src/views/onboarding/Onboarding.tsx

* SELC-1716 Fixed the auto-fill bug when we switch from another institutionType to a "PSP" institutionType
* SELC-1716 Little improvement in code

SELC-1716 Fixed the auto-fill bug when we switch from another institutionType to a "PSP" institutionType

---

package.json
src/components/autocomplete/components/AsyncAutocompleteResults.tsx
yarn.lock

SELC-1721 Resolved accessibility problem in the select party unreleated of both flows of onboarding

---

src/locale/it.ts
src/views/OnBoardingSubProduct/components/SubProductStepSelectUserParty.tsx
src/views/onboarding/Onboarding.tsx

* Correct typo
* change text in onboarding success page

Correct typo

---

src/components/steps/StepBillingData.tsx
src/locale/it.ts
src/views/OnBoardingSubProduct/__tests__/OnboardingSubProduct.test.tsx
src/views/onboarding/__tests__/Onboarding.test.tsx

* SELC-1768 Add logic for show spec title in function of institutionType and product selected
* Fixed unitTests

SELC-1768 Add logic for show spec title in function of institutionType and product selected

---

src/components/BodyLogger.tsx
src/components/Main.tsx
src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/steps/StepOnboardingFormData.tsx
src/locale/it.ts
src/model/BillingData.ts
src/model/OnboardingFormData.ts
src/views/NoProductPage.tsx
src/views/OnBoardingSubProduct/__tests__/OnboardingSubProduct.test.tsx
src/views/OnBoardingSubProduct/components/SubProductStepSubmit.tsx
src/views/onboarding/Onboarding.tsx
src/views/onboarding/__tests__/Onboarding.test.tsx

* added  geographicTaxonomies: [] on submit to fix BE error
* Fixed broken unitTest
Co-authored-by: esignore <elena.signore@nttdata.com>

added  geographicTaxonomies: [] on submit to fix BE error

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/onboardingFormData/taxonomy/GeoTaxSessionModal.tsx
src/components/onboardingFormData/taxonomy/GeoTaxonomySection.tsx
src/components/steps/StepOnboardingFormData.tsx
src/locale/it.ts
src/views/OnBoardingSubProduct/__tests__/OnboardingSubProduct.test.tsx
src/views/onboarding/__tests__/Onboarding.test.tsx

* SELC-1858 - added helperText
* SELC-1858 - added addModal and deleteModal

SELC-1858 - added modal (#397)

---

src/components/PlatformUserForm.tsx

* SELC-1976 - fixed error in PlatformUserForm if the email was entered without the previous fields

SELC-1976 - fixed error in PlatformUserForm

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/steps/StepOnboardingFormData.tsx
src/views/onboarding/__tests__/Onboarding.test.tsx

SELC-2108 - added fields rea, shareCapital and businessRegisterPlace

---

src/components/steps/StepInstitutionType.tsx
src/locale/it.ts
src/views/onboarding/__tests__/Onboarding.test.tsx

* SELC-2300 - added product name in page
* SELC-2300 - modified copy texts

SELC-2300 add product in page

---

.env.development.local
.env.test.local
src/services/tokenServices.ts
src/utils/unloadEvent-utils.ts
src/views/CompleteRegistrationComponent.tsx
src/views/RejectRegistration.tsx

* temp commit
* SELC-2174 - fixed rediret to login page if user is not loged in
* SELC-2174 -  fixed rediret to login page if user is not loged in
* SELC-2174 - modified error code
* SELX-2174 - added control in sigle api call

SELC-2174 party process to ms core (#561)

---

src/components/autocomplete/components/partyAdvancedSearchType/PartyAdvancedSelect.tsx
src/lib/__mocks__/mockApiRequests.ts
src/views/OnBoardingSubProduct/components/SubProductStepUserUnrelated.tsx
src/views/onboarding/Onboarding.tsx
src/views/onboarding/__tests__/Onboarding.test.tsx

* SELC-2489-show aoo/uo only for pn

SELC-2489-show aoo/uo only for pn

---

package.json
yarn.lock

Merge back from uat

---

package.json
yarn.lock

updated common and mui last version in order to allow onboarding of name and surname with dash character

SELC-2533 - updated common and mui last version in order to allow onboarding of name and surname with dash character

---

package.json
yarn.lock

updated common library to add new functionality that allow onboarding also for special characters
allow users add and onboarding for names with special characters
released in DEV and tested

SELC-2552-update-common-with-last-version

---

src/views/OnBoardingSubProduct/components/subProductStepPricingPlan/SubProductStepSelectPricingPlan.tsx

changed boolean in order to remove discount in onboarding premium
released in DEV and tested

Remove discount premium

---

.devops/deploy-pipelines.yml
.github/PULL_REQUEST_TEMPLATE.md
package.json
src/components/autocomplete/components/partyAdvancedSearchType/PartyAdvancedSelect.tsx
src/views/OnBoardingSubProduct/components/subProductStepPricingPlan/SubProductStepSelectPricingPlan.tsx
src/views/onboarding/__tests__/Onboarding.test.tsx
yarn.lock

removed temporaily aoo/uo select from all products
the aoo/uo have been temporarily shut down waiting for all developments to be completed
tested in DEV env

Selc 2589 remove temporarily aoo uo

---

.devops/deploy-pipelines.yml
.github/PULL_REQUEST_TEMPLATE.md
package.json
src/components/autocomplete/components/partyAdvancedSearchType/PartyAdvancedSelect.tsx
src/views/OnBoardingSubProduct/components/subProductStepPricingPlan/SubProductStepSelectPricingPlan.tsx
src/views/onboarding/__tests__/Onboarding.test.tsx
yarn.lock

* Update CODEOWNERS
* Update deploy-pipelines.yml
* SELC-2419
* SELC-2419 - SELC-2451
* docs: add pull request template
* SELC-2533 - updated common and mui last version in order to allow onboarding of name and surname with dash character
* SELC-2533 - updated common and mui last version in order to allow onboarding of name and surname with dash character
* removed discount for premium flow
* SELC-2552-update-common-with-last-version
* SELC-2589 - temporarily disabled aoo/uo for all products
* SELC-2589 - temporarily removed also tests
---------

Selc 2589 remove temporarily aoo uo (#622)

---

.devops/deploy-pipelines.yml

fixed env react_app_enable_pt variable

---

src/components/steps/StepInstitutionType.tsx

removed coalescing in order to fix visualization of institution type PSP for prod-io
fix bug

SELC-2694 - fixed visualization of institution type PSP for prod-io

---

src/components/steps/StepInstitutionType.tsx
src/locale/it.ts
src/views/onboarding/Onboarding.tsx
src/views/onboarding/components/OnboardingStep1_5.tsx

SELC-2713 modify error message

---

src/components/autocomplete/components/partyAdvancedSearchType/PartyAdvancedSelect.tsx
src/views/onboarding/__tests__/Onboarding.test.tsx

aoo/uo only shown for prod-interop

---

src/views/onboarding/__tests__/Onboarding.test.tsx

temporarily skipped tests

---

src/components/steps/StepInstitutionType.tsx
src/views/OnBoardingSubProduct/OnBoardingSubProduct.tsx
src/views/OnBoardingSubProduct/__tests__/OnboardingSubProduct.test.tsx
src/views/OnBoardingSubProduct/components/subProductStepPricingPlan/SubProductStepSelectPricingPlan.tsx

added a temporarily error message for prod-io-premium

SELC-2732-added error message for premium

---

src/views/onboarding/components/OnboardingStep1_5.tsx

modified error message also for party from IPA

SELC-2731 changed message for PA no allowed

---

src/views/onboarding/components/OnboardingStep1_5.tsx

modified messages if PA is not allowed

SELC-2731 changed message for PA no allowed (#648)

---

sonar-project.properties
src/lib/__mocks__/mockApiRequests.ts
src/locale/it.ts
src/views/UserNotAllowedPage.tsx
src/views/onboarding/Onboarding.tsx
src/views/onboarding/__tests__/Onboarding.test.tsx
src/views/onboarding/components/OnboardingStep1_5.tsx
types.ts

Added page for unauthorized users and some cases to replicate the situation locally. Also added some code and mock improvements
To cover the need to give feedback to users with the product in testing status, this page has been introduced

Not allowed users to product custom page + added use case to replicate in local + code and mocks improvements

---

src/components/PlatformUserForm.tsx
src/components/steps/StepOnboardingFormData.tsx

Email fields now accept domain with 5 max characters

Email fields now accept domain with 5 max characters

---

src/views/onboarding/Onboarding.tsx

SELC-2834 - added party cf if aoo or uo selected

---

src/components/steps/StepOnboardingFormData.tsx
src/utils/constants.ts

modified geotaxonomy endpoint in order to retrieve aoo/uo geotax

SELC-2834 - modified  geotaxonomy endpoint

---

src/components/steps/StepInstitutionType.tsx
src/views/OnBoardingSubProduct/OnBoardingSubProduct.tsx
src/views/OnBoardingSubProduct/components/subProductStepPricingPlan/SubProductStepSelectPricingPlan.tsx

SELC-3011  remove error page shown with Enable Banner env variable for prod-io and prod-io-premium
The page was not used. The same env variable is being used now with a different meaning. No longer only for prod-io and prod-io-premium

SELC-3011 remove error page shown with Enable Banner env variable

---

src/components/autocomplete/Autocomplete.tsx
src/components/autocomplete/components/partyAdvancedSearchType/PartyAdvancedSelect.tsx
src/components/steps/StepInstitutionType.tsx
src/components/steps/StepSearchParty.tsx
src/locale/it.ts
types.ts

SELC-3066
In order to allow SA from ANAC to onboard new radion button created.
Test locally the application

SELC-3066 add new radio button for SA institutionType

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/steps/StepOnboardingFormData.tsx
src/locale/it.ts

SELC-3070
adapt fill form page for SA institutions
test locally with mocked api

SELC-3070 adapted fill form data page

---

src/views/onboarding/Onboarding.tsx

fix for fiscal code in id
adapt FE after BE fix 
test integration locally

SELC-3067_fix-fiscalCode

---

src/components/BodyLogger.tsx

Disabled the assistanceButton in the header only for UAT environment
In order to not allow users to send requests for support in a UAT environment

SELC-3084 Disabled the assistanceButton in the header only for UAT environment

---

src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx
src/utils/constants.ts
src/views/onboarding/__tests__/Onboarding.test.tsx

Optimized filtered categories search
Cleaner code that cover GSP search case and also include AOO/UO search for all categories

Optimized filtered categories search

---

src/components/onboardingFormData/taxonomy/__tests__/GeoTaxonomySection.test.tsx
src/setupTests.ts
src/utils/test-utils.tsx

unit tests for geo taxonomy

---

src/components/autocomplete/components/partyAdvancedSearchType/PartyAdvancedSelect.tsx

Added MenuItems AOO and UO for prod-io-sign
In order to allow possible onboarding of AOO and UO also for prod-io-sign
Tested with local start and aiming to dev environment data

SELC-3106 Added onboarding for AOO and UO for io-sign

---

src/components/autocomplete/components/partyAdvancedSearchType/PartyAdvancedSelect.tsx
src/components/onboardingFormData/taxonomy/__tests__/GeoTaxonomySection.test.tsx
src/setupTests.ts
src/utils/test-utils.tsx

- SELC-3106 Added AOO/UO for io sign
As request, we include AOO and UO choice for onboarding for io-sign product.
Added unit test for geotaxonomy.
Started in local and aiming dev environment

SELC-3106 Added AOO/UO for io sign + unit test geotaxonomy

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/onboardingFormData/__tests__/PersonalAndBillingDataSection.test.tsx
src/components/steps/StepOnboardingFormData.tsx

Remove SDI input field for PT
When onboarding as PT SDI field is not required

SELC-3169 remove SDI input field for PT

---

src/components/autocomplete/components/partyAdvancedSearchType/PartyAdvancedSelect.tsx
src/lib/__mocks__/mockApiRequests.ts

Enable AOO and UO in uat for prod-pn-dev

Enable AOO and UO in uat for prod-pn-dev

---

package.json
src/components/BodyLogger.tsx
src/utils/env.ts
yarn.lock

SELC-3135 add docs button in header
Update common library

SELC-3135 add docs button in header and update common

---

package.json
sonar-project.properties
src/components/BodyLogger.tsx
src/components/PlatformUserForm.tsx
src/lib/__mocks__/mockApiRequests.ts
src/utils/env.ts
src/views/OnBoardingSubProduct/__tests__/OnboardingSubProduct.test.tsx
src/views/OnBoardingSubProduct/components/SubProductStepVerifyInputs.tsx
src/views/onboarding/Onboarding.tsx
src/views/onboarding/__tests__/Onboarding.test.tsx
src/views/onboarding/components/OnBoardingProductStepDelegates.tsx
yarn.lock

Skipped manager step for techPartner onboarding flow
In order to have the techPartner experience onboarding as request
Started locally and aiming environment data dev

SELC-3172 Skipped manager step for techPartner onboarding flow

---

src/components/PlatformUserForm.tsx
src/views/onboarding/Onboarding.tsx

Remove loader and fixed bug that show error in taxCode field when empy for third administrator
Resolves error reporting to third administrator when taxcode field is empty
Local execution and aiming dev environment data

Remove loader and fixed bug that show error in taxCode field when empy for third administrator

---

src/views/onboarding/Onboarding.tsx
src/views/onboarding/components/OnBoardingProductStepDelegates.tsx

Correct submit payload for techPartner
In order to submit only users array with elements

Correct submit payload for techPartner

---

src/components/PlatformUserForm.tsx
src/views/onboarding/Onboarding.tsx
src/views/onboarding/components/OnBoardingProductStepDelegates.tsx

Remove loader and fixed bug that show error in taxCode field when empy for third administrator
In order to remove loader when forward from billing data to manager or directly to delegates (in case of tech partner)
Locally and aiming DEV environment data

Remove loader and fixed bug that show error in taxCode field when empty for third administrator

---

src/components/steps/StepInstitutionType.tsx
src/locale/it.ts
types.ts

SELC-3217 Add new radio button for Insurance companies with institution type AS
Add new radio button to allow Insurance companies to onboard on product interop
Tested locally

SELC-3217 Add new radio button for institution type AS

---

src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx
src/components/autocomplete/components/partyAdvancedSearchType/PartyAdvancedSelect.tsx
src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/steps/StepSearchParty.tsx
src/lib/__mocks__/mockApiRequests.ts
src/locale/it.ts
src/utils/constants.ts
types.ts

SELC-3226 Allow insurance companies to search themselves by their company name during onboarding in interop
During thonboarding process to interop insurance companies should be able to use the search input to look for their company using the busniess name.
Test locally with mocked data and integration test with real api

[SELC-3226] feat: Search AS by their company name

---

src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx
src/views/onboarding/__tests__/Onboarding.test.tsx

Block on typing special characters in institution search
In order to minimize retrieve party list API call errors, the special characters are blocked on typing. Relative unitTest added too.
Local execution and unit test.

[SELC-3282] feat: Block on typing special characters in institution search

---

src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx
src/utils/constants.ts

Added uncovered special characters
Added missed special characters
Local execution

[SELC-3282] feat: Added uncovered special characters

---

src/components/steps/StepOnboardingFormData.tsx
src/lib/__mocks__/mockApiRequests.ts
src/utils/constants.ts
src/views/OnBoardingSubProduct/components/SubProductStepOnBoardingStatus.tsx
src/views/onboarding/Onboarding.tsx
src/views/onboarding/components/OnboardingStep1_5.tsx

Add subunitCode dor AOO and UO in verifyOnboarding api call
Removed deprecated verifyOnboarding api call and switched it with the new one.
Found bug during onboarding of uo if the central institution was already onboarded. Verify onboarding needs optional parameter subunitCode
Test locally and tested in dev.

[SELC-3292] fix: onboarding with UO error if central institution is already onboarded

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/lib/__mocks__/mockApiRequests.ts
types.ts

Change the name of var istat_code to istatCode

[SELC-3362]_fix: typo of istat code

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/lib/__mocks__/mockApiRequests.ts
types.ts

Change the name of variable istat_code to istatCode

[SELC-3362] fix: typo of istat code

---

src/components/steps/StepOnboardingFormData.tsx
src/views/OnBoardingSubProduct/__tests__/OnboardingSubProduct.test.tsx
src/views/onboarding/Onboarding.tsx
src/views/onboarding/__tests__/Onboarding.test.tsx

Updated payload of onboarding submit in case of institution from IPA
City and province are required fields now for all institution types.
During onboarding process the location data should be sent for institutions with origin from IPA.

[SELC-3366] feat: Add institutionLocationData to onboarding submit

---

src/components/steps/StepOnboardingFormData.tsx
src/views/OnBoardingSubProduct/__tests__/OnboardingSubProduct.test.tsx
src/views/onboarding/Onboarding.tsx
src/views/onboarding/__tests__/Onboarding.test.tsx

Updated payload of onboarding submit in case of institution from IPA
City and province are required fields now for all institution types.
During onboarding process the location data should be sent for institutions with origin from IPA.
Tested in dev enviroment

[SELC-3366] feat: Add field institutionLocationData to onboarding submit

---

src/components/PlatformUserForm.tsx
src/components/onboardingFormData/DpoSection.tsx
src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/steps/StepOnboardingFormData.tsx

Changed fontSize and fontWeight basing disabled field+minor improvements
The goal is to keep all text formats in their various states (disabled or not) consistent throughout onboarding
Local execution of the entire onboarding flow for all institutionType

[SELC-3377] feat: Changed fontSize and fontWeight basing disabled field+minor improvements

---

src/components/onboardingFormData/NumberDecimalFormat.tsx
src/components/onboardingFormData/PersonalAndBillingDataSection.tsx

Added bold to reaCapital and supportEmail
added bold to reaCapital and supportEmail to missing input fields

[SELC-3377] fix: added bold to reaCapital and supportEmail

---

src/views/OnBoardingSubProduct/components/SubProductSubmitFetch.ts

Added institutionLocationData object in submit payload for premium onboarding flow
In order to save locationData also for parties that do an adhesion for premium product
Aiming DEV environment, the InstitutionLocationData with city, country and county is present and with correct informations

[SELC-3441] feat: Added institutionLocationData object in submit payload for premium onboarding flow

---

src/components/PlatformUserForm.tsx
src/views/onboarding/__tests__/Onboarding.test.tsx
src/views/onboarding/components/OnBoardingProductStepDelegates.tsx

Responsive extra delegates forms
In order to make the form of additional controls is responsive to changes in the dimensions of the screen.
Shrinking the browser (for example opening the inspector), also the extra delegate forms decrease dimensions

[SELC-2532] feat: Responsive extra delegates forms

---

src/components/ConfirmOnboardingRequest.tsx
src/components/steps/StepAddManager.tsx
src/locale/it.ts
src/views/OnBoardingSubProduct/OnBoardingSubProduct.tsx
src/views/onboarding/Onboarding.tsx
src/views/onboarding/__tests__/Onboarding.test.tsx
src/views/onboarding/components/OnBoardingProductStepDelegates.tsx

New confirm onboarding request modal before sending the submit call.
At the end of the onboarding flow ask the user to confirm it wants to send the onboarding request.
Tested locally and unit test

[SELC-2836] feat: New confirm onboarding request modal 

---

src/components/steps/StepSearchParty.tsx
src/locale/it.ts

Add Link to AgID certification docs for institution type SA
An institution thats onboarding to prod interop should be able to click link to AgID certification docs in the search you institution page
Tested in local enviroment.

[SELC-3453] feat: Add Link to AgID certification docs for SA

---

src/components/autocomplete/components/partyAdvancedSearchType/PartyAdvancedSelect.tsx

Aoo and uo option for party search enabled for send
For allow onboarding from aoo / uo parties also for SEND product

feat: aoo and uo option for party search enabled for send

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx

Add limit of 7 charachters to sdi code input field.
If the user writes more than 7 characters in the sdi code input field then the integration with SAP break.

[SELC-3498] feat: Add limit of 7 charachters to sdi code

---

src/components/steps/StepInstitutionType.tsx

Temporary disabled psp onboarding for product pagopa

feat: temporary disabled psp onboarding for product pagopa

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx

SELC-3496_graphic-fix 
Tested in local

SELC-3496_graphic-fix

---

src/components/steps/StepInstitutionType.tsx

Temporary disabled psp radiobutton for prod-pagopa
Feature already available in production environment, this is the alignment of the branches after the hotfix to main branch

feat: temporary disabled psp radiobutton for prod-pagopa

---

src/components/steps/StepOnboardingData.tsx

capitalize first Letter of city

SELC-3496_capitalize-firstLetter

---

src/components/steps/StepOnboardingFormData.tsx
src/lib/__mocks__/mockApiRequests.ts

Fixed validation form trigger
In order to manage correctly the disabled and not-disabled of confirm button
In local with a mock case

fix: validation form trigger

---

package.json
yarn.lock

update selfcare-common-frontend dependency
New label in footer for privacy policy

[SELC-1712] feat: update selfcare-common-frontend dependency

---

.devops/deploy-pipelines.yml
.env.development.local
.env.test.local
src/utils/constants.ts
src/utils/env.ts

Add react_app_url_api_onboarding_v2 for dev uat and prod
To allow testing for new basepath v2 add new env variable.

Add new env variable for onboarding v2 base path

---

src/utils/constants.ts

Onboarding verify chane base path to V2

---

.env.development.local
.env.test.local
src/utils/env.ts

Fixed environment variable definition typo
Fixed wrong name of the environment variable

[SELC-3612] fix: Fixed environment variable definition typo

---

src/components/steps/StepOnboardingFormData.tsx

feat: temp commented code waiting for prod-fd resolution

---

src/locale/it.ts
src/views/OnBoardingSubProduct/components/subProductStepPricingPlan/SubProductStepSelectPricingPlan.tsx

Added dynamic carnet counter
In order to have correct number of carnet always, also if a carnet is deleted or added new one
Tested in local, the carnet number is updated

feat: Added dynamic carnet counter

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/onboardingFormData/__tests__/PersonalAndBillingDataSection.test.tsx
src/components/steps/StepOnboardingFormData.tsx

code optimization for recipient code condition

Simplify recipient code visibility logic

---

src/utils/constants.ts

Fix the condition that was not reading the full api path for v2 in Dev

Fix: missing api path for v2

---

src/components/RadioWithTextField.tsx
src/locale/it.ts
src/views/onboarding/Onboarding.tsx
src/views/onboarding/components/StepAdditionalInfos.tsx

Created StepAdditionalInfos rendered at the expected conditions
In order to collect necessary informations for public service managers seeking to join the PagoPA Payments product, this new step has been created to collect this information. It will be displayed only for public service managers
Tested in local, the new step is rendered only at the expected condition and all checks works well

[SELC-3789] feat: Created StepAdditionalInfos rendered at the expected conditions

---

src/index.css
src/index.tsx

Overwrite the font family for cookie banner to Titillium web.

[SELC-1294] feat: change font family cookie banner

---

src/index.css
src/index.tsx

Change font family of cookie banner to Titillium web

[SELC-1294] feat: change font family of cookie banner 

---

src/locale/it.ts
src/views/onboarding/components/StepAdditionalInformations.tsx

Improvement on validation + fix wrong text
Validation was not always triggered correctly and two incorrect texts were corrected
Tested in local, validation cover the case that was uncovered and the text are now correct

feat: improvement on validation + fix wrong text

---

src/utils/constants.ts

add /v2 to path of new onboarding api calls 
remove condition for env === dev in constants file
Removed /v2 from the env variables and added it to FE api path
remove condition for env === dev in constants file and added diffent base url based on env variable in selfcare-azure-devops

[SELC-2868] feat: add /v2 to path of new onboarding api  calls

---

src/utils/constants.ts

Add slash to onboarding v2 URL

[SELC-2868]_fix: add missing slash in URL

---

src/locale/it.ts

Changed label of concessionaireOfPublicService
Change request: in order to give some experience in onboarding flow and admin overview
Tested in local environment, the label is updated

feat: changed label of concessionaireOfPublicService

---

src/views/onboarding/Onboarding.tsx

Changed properties sended in submit for align at BE modifies

feat: Changed properties sended in submit for align at BE modifies

---

src/locale/it.ts

Change copy of error message.
During verification of P.IVA in onboarding to prod-fd change the error message shown

[SELC-3747] feat: Change copy of error message

---

src/locale/it.ts
src/utils/constants.ts
src/views/onboarding/Onboarding.tsx

SELC-2868 + minors

---

src/utils/constants.ts

fix: restored basePath

---

src/views/onboarding/Onboarding.tsx

back button wrong redirect in case of techPartner + submit adaptations

---

src/utils/constants.ts

fix path of verify api url

---

src/utils/constants.ts

fix path of verify onboarding v2

---

src/utils/constants.ts

add to the URL of the api "/v2" in dev enviroment

Add onboarding add "/v2" from frontend

---

src/views/OnBoardingSubProduct/OnBoardingSubProduct.tsx
src/views/OnBoardingSubProduct/components/subProductStepPricingPlan/SubProductStepSelectPricingPlan.tsx

Check on available pricingplansIds based on REST response
Resolve the previous static approach that expect as correct pricingPlanId only those indicated by the condition. With this implementation is used a dynamic approach also for validation of correct pricingPlanId
Tested in local environment, if pricingPlan is correct, the user is authorized to proceed with onboarding flow

feat: Check on available pricingplansIds based on REST response

---

src/components/steps/StepAddManager.tsx
src/components/steps/StepOnboardingFormData.tsx
src/utils/api/userValidate.ts
src/views/OnBoardingSubProduct/OnBoardingSubProduct.tsx
src/views/OnBoardingSubProduct/components/SubProductStepSelectUserParty.tsx
src/views/OnBoardingSubProduct/components/SubProductStepUserUnrelated.tsx
src/views/OnBoardingSubProduct/components/SubProductSubmitFetch.ts
src/views/OnBoardingSubProduct/components/subProductStepPricingPlan/SubProductStepSelectPricingPlan.tsx
src/views/OnBoardingSubProduct/components/subProductStepPricingPlan/components/carnetPlanComponent/FooterCarnet.tsx
src/views/OnBoardingSubProduct/components/subProductStepPricingPlan/components/consumptionPlanComponent/FooterConsumptionCard.tsx

Added missing event in onboarding io premiuim flow 
Changed events called in wrong place.
Add missing properties in payload object
In order to follow the user jorney during onboarding to prod-io-premuim and to be able to track in through mix panel added events that can be traced in mix panel dashboard.
Tested by aiming at dev data.

[SELC-2278] Feat: Integration with mix panel events for premium flow

---

src/components/steps/StepAddManager.tsx
src/components/steps/StepInstitutionType.tsx
src/locale/it.ts
src/views/onboarding/components/OnBoardingProductStepDelegates.tsx

Added roles link documentation and changed copy
In order to align the pages at the last modifies required UI/UX mockups
Tested in local

[SELC-3974] feat: Added roles link documentation+changed copy

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx

When clicking back on form the city and county should be prefilled.
Tested locally

[SELC-3926] Fix: Persist city and county data 

---

src/views/onboarding/Onboarding.tsx

Retrieving and save institutionType from queryParams
In order to allow the adhesion for techPartner at prod-pagopa without clicking the radiobutton, directly saving the institutionType from queryparam
Typing the url /onboarding/prod-pagopa?institutionType=PT, automatically forward to step insert data and saving the institutionType (PT)

[SELC-4082] feat: Retrieving and save institutionType from queryParams

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/views/onboarding/Onboarding.tsx

Release in UAT of persist city and county data and retrieving and save the institutionType from queryparams
In order to allow the adhesion for techPartner at prod-pagopa without clicking the radiobutton, directly saving the institutionType from queryparam and improve UX
The improvement and the retrieving institutionType from queryparams are all tested in DEV, typing the url /onboarding/prod-pagopa?institutionType=PT, automatically forward to step insert data and saving the institutionType (PT)

feat: SELC-3926 SELC-4082

---

src/components/steps/StepSearchParty.tsx
src/locale/it.ts

Changed copy and added missed localization
In order to offer a more specific description
In local, the text is correctly localized with new text provided

[SELC-4042] feat: Changed copy and added missed localization

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/model/BillingData.ts
src/views/onboarding/__tests__/Onboarding.test.tsx

The SDI code input will be transformed to upper case when filling the input field
In order to resolve issue with SAP where it would ignore invocies with sdi code in lower case.
Tested locally

[SELC-4078] Feat: Transform SDI code to Uppercase

---

src/views/OnBoardingSubProduct/OnBoardingSubProduct.tsx

Add mixpanel event ONBOARDING_PREMIUM_UX_CONVERSION when confirming onboarding request for subproducts
Tested locally

[SELC-4117] Feat: Add mixpanel event ONBOARDING_PREMIUM_UX_CONVERSION

---

src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx
src/components/steps/StepOnboardingFormData.tsx
src/components/steps/StepSearchParty.tsx
src/lib/__mocks__/mockApiRequests.ts
src/locale/it.ts
src/views/onboarding/__tests__/Onboarding.test.tsx

Added new categories filter+edited disclaimer
New categories can onboard on SEND, then the category filters include this too
Tested in DEV, the categories are correctly found

[SELC-4052] feat: Added new categories filter+edited disclaimer

---

src/components/steps/StepAddManager.tsx
src/components/steps/StepInstitutionType.tsx
src/components/steps/StepSearchParty.tsx
src/locale/it.ts
src/views/OnBoardingSubProduct/components/SubProductStepOnBoardingStatus.tsx
src/views/OnBoardingSubProduct/components/SubProductStepSelectUserParty.tsx
src/views/OnBoardingSubProduct/components/SubProductStepSuccess.tsx
src/views/OnBoardingSubProduct/components/SubProductStepUserUnrelated.tsx
src/views/onboarding/Onboarding.tsx
src/views/onboarding/components/OnBoardingProductStepDelegates.tsx

Transform the name of the products in bold
Tested locally

[SELC-4119] Feat: Name of the product writen in bold 

---

src/components/steps/StepAddManager.tsx
src/components/steps/StepInstitutionType.tsx
src/components/steps/StepSearchParty.tsx
src/locale/it.ts
src/views/OnBoardingSubProduct/components/SubProductStepOnBoardingStatus.tsx
src/views/OnBoardingSubProduct/components/SubProductStepSelectUserParty.tsx
src/views/OnBoardingSubProduct/components/SubProductStepSuccess.tsx
src/views/OnBoardingSubProduct/components/SubProductStepUserUnrelated.tsx
src/views/onboarding/Onboarding.tsx
src/views/onboarding/components/OnBoardingProductStepDelegates.tsx

Transform the product name in bold wherever is shown in onboarding flow.
Tested in dev

[SELC-4119] Feat: Make The name of the product in bold

---

src/components/onboardingFormData/ErrorPIVAModal.tsx
src/components/steps/StepOnboardingFormData.tsx
src/locale/it.ts

In the onboarding flow to prod-fd add a modal in case of generic error from BE during verification of vat number
For techincal problems with the product fiddeiussioni the BE returns status code 500. Add modal that allows redirct to select institutions in dashboard.

[SELC-3966] Feat: Modal for iva generic error

---

src/components/autocomplete/components/partyAdvancedSearchType/PartyAdvancedSelect.tsx

Hide the options of searching by aoo / uo code for institutions of type gsp in all products.
GSP are not allowwed to search institutions by aoo / uo code
Tested locally

[SELC-4259] Feat: Institutions of type GSP can not search by aoo / uo code

---

src/components/autocomplete/components/partyAdvancedSearchType/PartyAdvancedSelect.tsx

Hide the options of searching by aoo / uo code for institutions of type gsp in all products.
GSP are not allowwed to search institutions by aoo / uo code
Tested in dev

[SELC-4259] Feat: disable search by aoo /uo code for gsp

---

src/utils/constants.ts

Aiming new onboarding dev and uat
In order to aiming the new onboarding v2 also in UAT
Tested in DEV, all the REST API respond as expected

feat: Aiming new onboarding dev and uat

---

src/components/steps/StepOnboardingFormData.tsx
src/lib/__mocks__/mockApiRequests.ts
src/locale/it.ts
src/views/onboarding/Onboarding.tsx
src/views/onboarding/components/OnBoardingProductStepDelegates.tsx

Copy change for pt institutions from direct link
With the new flow to allow pt to onboardond to prod-pagopa from direct link its necessary to make some copy changes.
Tested locally

[SELC-4264] Feat: copy change for pt institutions from direct link

---

src/components/steps/StepSearchParty.tsx
src/locale/it.ts

Replace old banner with categories that can onboard on SEND with new banner with link to pagopa docs that contains the categories.
In order to follow new design guidelines.
Tested in local

[SELC-4298] Feat: change banner for SEND

---

src/components/steps/StepSearchParty.tsx

change alert type for send banner from warning to info
Tested locally

[SELC-4298] Feat: change alert type of send banner to info

---

src/utils/constants.ts

Removed disambiguation based on environment
In order to aim always to the new onboarding microservices

feat: Removed disambiguation based on environment

---

src/utils/constants.ts

feat: branch alignment after hotfix

---

src/components/RadioWithTextField.tsx
src/components/steps/StepSearchParty.tsx
src/locale/it.ts
src/utils/constants.ts

change maxlength of IPA code input from 6 to 16.
change color of send banner.
Tested in dev

[SELC-4263] Feat: change maxlength of IPA code input to 16

---

src/components/steps/StepAddManager.tsx
src/views/onboarding/components/OnBoardingProductStepDelegates.tsx

change link of more info about roles in legal rappresentative page
change link in administrators page
In order to follow new figma design.
Tested locally

[SELC-4368] Feat: change links of more info about roles

---

src/components/steps/StepOnboardingFormData.tsx

Remove comments for verfiy vat number
Removed commented code after test are done in uat.

Enable verify vat number for prod-fd

---

src/components/steps/StepOnboardingFormData.tsx

Enable verify vatnumber for prod-fd

---

src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx
src/components/steps/StepOnboardingFormData.tsx
src/components/steps/StepSearchParty.tsx
src/views/onboarding/__tests__/Onboarding.test.tsx

Added L15 and C14 in allowed categories
in order to open the onboarding on product SEND to 2 new categoris.

[SELC-4453] Feat: Allow L15 and C14 categories to onboard in SEND

---

src/views/onboarding/components/OnBoardingProductStepDelegates.tsx

New doc link
For tech partners a new documentation link was added in the sign your admin page.
Tested locally

[SELC-4485] Feat: New documentation link for tech partners

---

src/components/ConfirmRegistrationStep0.tsx
src/components/ConfirmRegistrationStep1.tsx
src/components/FileUploader.tsx
src/locale/it.ts
src/views/__tests__/CompleteRegistrationComponent.test.tsx

Create new page for allow upload and download adhesion contract+changed text after copy modifies
UI changed and also added the possibility to download the adhesion contract in order to offer best experience during the final steps of adhesion
Tested in local, the page and the text is showed like the mockup

[SELC-4455] feat: Create new page for allow upload and download adhesion contract+changed text after copy modifies

---

src/components/BodyLogger.tsx

hide documentation button
The documentation of selfcare at the moment is only in italian so it should not be avaible to other languages

[SELC-4492] Feat: hide documentation button for non italian language

---

src/views/OnBoardingSubProduct/OnBoardingSubProduct.tsx

graphic fix

---

src/components/ConfirmRegistrationStep0.tsx
src/utils/constants.ts

[SELC-4457] feat: Added getContract API call to download the adhesion contract
In order to allow the party to download the adhesion contract this api call was introduced. It's called when the button for download is clicked making available a .pdf extension file
Tested in DEV environment, when the button is clicked, the api is triggered and a contract with extension .pdf is downloaded
[SELC-4457]: https://pagopa.atlassian.net/browse/SELC-4457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-4457] feat: Added getContract API call to download the adhesion contract

---

src/components/ConfirmRegistrationStep0.tsx
src/services/tokenServices.ts
src/utils/getRequestJwt.ts
src/views/uploadContract/cancel/CancelRequestComponent.tsx
src/views/uploadContract/cancel/__tests__/CancelRequestComponent.test.tsx
src/views/uploadContract/complete/CompleteRequestComponent.tsx
src/views/uploadContract/complete/__tests__/CompleteRequestComponent.test.tsx

feat: Little refactor for remove duplicate code

---

CODEOWNERS
src/components/ConfirmRegistrationStep0.tsx
src/services/tokenServices.ts
src/utils/constants.ts
src/utils/getRequestJwt.ts
src/views/uploadContract/cancel/CancelRequestComponent.tsx
src/views/uploadContract/cancel/__tests__/CancelRequestComponent.test.tsx
src/views/uploadContract/complete/CompleteRequestComponent.tsx
src/views/uploadContract/complete/__tests__/CompleteRequestComponent.test.tsx

Co-authored-by: Manuel Rafeli <manuel.rafeli@pagopa.it>
Co-authored-by: loremedda <98110186+loremedda@users.noreply.github.com>

[SELC-4481] Feat:  Substitute deprecated api call instituion-info (#877)

---

src/views/uploadContract/complete/CompleteRequestComponent.tsx

fix: Remove unuset method

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/steps/StepOnboardingFormData.tsx
src/locale/it.ts
src/model/BillingData.ts
src/model/OnboardingFormData.ts
src/views/onboarding/Onboarding.tsx

[SELC-4463] feat: Changes in the onboardingFormData component to allow the onboarding also for foreign insurance companies
Changes made in order to allow the onboarding also for the foreign insurance company, 
Tested in local and dev environment ensuring that the data will be send correctly at the submit
[SELC-4463]: https://pagopa.atlassian.net/browse/SELC-4463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-4463] feat: Changes in the onboardingFormData component to allow the onboarding also for foreign insurance companies

---

src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx
src/components/autocomplete/components/asyncAutocomplete/components/AsyncAutocompleteResultsCode.tsx

feat: ivass entity selection

---

src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx
src/components/autocomplete/components/asyncAutocomplete/components/AsyncAutocompleteSearch.tsx
src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/steps/StepOnboardingFormData.tsx
src/model/BillingData.ts
src/model/OnboardingFormData.ts

- Removed italy from countries state
- Removed todo's
- Showed name of insurance company
- Other minors
- Added todo reminder for helpertext showed when users digits number in search city textfield for foreign ensurance companies

feat: some minor changes

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/steps/StepOnboardingFormData.tsx
src/lib/__mocks__/mockApiRequests.ts
src/model/BillingData.ts
src/views/onboarding/__tests__/Onboarding.test.tsx
types.ts

Managed also the non-existance taxCode case for a future perspective

feat: Managed also the non-existance taxCode case for a future perspective

---

src/views/onboarding/Onboarding.tsx
src/views/onboarding/components/OnboardingStep1_5.tsx

[SELC-4721] feat: Provide the origin and originId parameters to verifyOnboarding REST API
Some parameters have been added in the REST call to cover insurance opt-ins. In cases where this REST call is invoked by the client, the origin and originId parameters were passed, as these are optional and were passed only at the points where the call is actually inserted in the insurance onboarding flow
Tested aiming the dev environment, the expected parameters in the api call invoked for insurance company adhesion are correctly provided
[SELC-4721]: https://pagopa.atlassian.net/browse/SELC-4721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-4721] feat: Provide the origin and originId parameters to verifyOnboarding REST API

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/steps/StepOnboardingFormData.tsx
src/locale/it.ts

[SELC-4742] feat: Disabled ivassCode field
The ivassCode is a disabled field because is a data retrieved from a certified source
Tested in local environment, the ivassCode is now disabled
[SELC-4742]: https://pagopa.atlassian.net/browse/SELC-4742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-4742] feat: Disabled ivassCode field

---

src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx
src/components/onboardingFormData/Heading.tsx
src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/onboardingFormData/VatNumberErrorModal.tsx
src/components/onboardingFormData/__tests__/PersonalAndBillingDataSection.test.tsx
src/components/onboardingFormData/taxonomy/UpdateGeotaxonomy.tsx
src/components/steps/StepOnboardingData.tsx
src/components/steps/StepOnboardingFormData.tsx
src/components/steps/StepSearchParty.tsx
src/lib/__mocks__/mockApiRequests.ts
src/utils/constants.ts
src/utils/handleGeotaxonomies.ts
src/utils/validateFields.ts
src/views/onboarding/__tests__/Onboarding.test.tsx

[SELC-4607] feat: Refactor StepOnboardingData + added form field unitTests
The coverage of unit tests has been increased, covering all the foreseen entity/product type intersections, the conditions have been revised, and specific components have been created to make the code more streamlined.
Tested with unitTest and behaviour tests made upstream in such a way as to take the pre-refactor situation as correct. Following the refactor, unit tests reported no anomalies and behavioral tests returned the expected results
[SELC-4607]: https://pagopa.atlassian.net/browse/SELC-4607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-4607] feat: Refactor StepOnboardingData + added form field unitTests

---

src/components/steps/StepOnboardingFormData.tsx

[SELC-4833] feat: Added businessRegisterPlace/rea/shareCapital fields for not ipa gps and scp for prod pagopa
Following a change to the membership contract, the need arose to show these fields to the user in order to collect the respective data during the onboarding process
Tested in local, the field are now available for the use case expected
[SELC-4833]: https://pagopa.atlassian.net/browse/SELC-4833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-4833] feat: Added businessRegisterPlace/rea/shareCapital fields for not ipa gps and scp for prod pagopa

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/onboardingFormData/__tests__/PersonalAndBillingDataSection.test.tsx
src/components/steps/StepOnboardingFormData.tsx
src/lib/__mocks__/mockApiRequests.ts
src/locale/it.ts
src/model/OnboardingFormData.ts
src/model/UoModel.ts
src/utils/validateFields.ts
src/views/onboarding/Onboarding.tsx
src/views/onboarding/__tests__/Onboarding.test.tsx

[SELC-4792] feat: Added new input field SFETaxCode for uo, reading it from rest api call and shown if present + added mock cases
It was necessary to have this data which we recover from a data source or have the institution enter manually
Tested in local environment with mocks and aiming dev data from local, the data is correctly retrieved when available and the field is respectively filled
[SELC-4792]: https://pagopa.atlassian.net/browse/SELC-4792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

 [SELC-4792] feat: Added new input field SFETaxCode for uo, reading it from rest api call and shown if present + added mock cases

---

src/components/PlatformUserForm.tsx
src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/steps/StepOnboardingFormData.tsx
src/locale/it.ts
src/model/BillingData.ts
src/model/OnboardingFormData.ts
src/views/onboarding/Onboarding.tsx
yarn.lock

[SELC-4825] feat: Provided taxCodeInvoicing value at submit POST + some style corrections
The taxCodeInvoicing, that is retrieved from the microservice or by inserting from party, is sent to the API Rest submit in order to be persisted
Tested in local and dev environment
[SELC-4825]: https://pagopa.atlassian.net/browse/SELC-4825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-4825] feat: Provided taxCodeInvoicing value at submit POST + some style corrections

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/lib/__mocks__/mockApiRequests.ts
src/locale/it.ts
src/model/UoModel.ts
src/views/onboarding/Onboarding.tsx

[SELC-4853] feat: Changed taxCode label for aoo/uo + disabled field
Change request for improve user experience
Tested in local environment
[SELC-4853]: https://pagopa.atlassian.net/browse/SELC-4853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-4853] feat: Changed taxCode label for aoo/uo + disabled field

---

src/components/onboardingFormData/Heading.tsx
src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/steps/StepOnboardingFormData.tsx
src/locale/it.ts
src/views/OnBoardingSubProduct/OnBoardingSubProduct.tsx
src/views/onboarding/Onboarding.tsx

[SELC-4818] feat: Removed unexpected translation tag + removed unnecessary prop from custom component
In order to remove the unexpected tag from translation string
Tested in local environment, the translation of text not show unexpected tags
[SELC-4818]: https://pagopa.atlassian.net/browse/SELC-4818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-4818] feat: Removed unexpected translation tag + removed unnecessary prop from custom component

---

src/locale/it.ts
src/views/onboarding/Onboarding.tsx
src/views/onboarding/__tests__/Onboarding.test.tsx
src/views/onboarding/components/OnboardingStep1_5.tsx

[SELC-4616] feat: Changed copy for already onboarded outcome + added icon
[SELC-4616]: https://pagopa.atlassian.net/browse/SELC-4616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-4616] feat: Changed copy for already onboarded outcome + added icon

---

src/components/steps/StepOnboardingFormData.tsx

[SELC-4817] fix: Correctly pre-filled vatNumber
Prefilled textfield correctly when vatNumber is present
The use case has been replicated in the local environment, the vatNumber is correctly pre-filled when present and sent or not to the submit (both of the basic and premium flows)
[SELC-4817]: https://pagopa.atlassian.net/browse/SELC-4817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-4817] fix: Correctly pre-filled vatNumber

---

package.json
src/components/RolesInformations.tsx
src/components/steps/StepAddManager.tsx
src/locale/it.ts
src/views/onboarding/Onboarding.tsx
src/views/onboarding/components/OnBoardingProductStepDelegates.tsx
src/views/onboarding/components/OnboardingStep1_5.tsx
yarn.lock

[SELC-4372] feat: Added the addNewAdmin entrypoint link in the alreadyOnboarded page
Give the legal representatives who take over the opportunity to access in the portal adding themselves as administrators of the institution
Tested in local environment, the link appears correctly in the already onboarded page
[SELC-4372]: https://pagopa.atlassian.net/browse/SELC-4372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-4372] feat: Added the addNewAdmin entrypoint link in the alreadyOnboarded page

---

src/components/OnboardingStepActions.tsx
src/components/PlatformUserForm.tsx
src/components/RolesInformations.tsx
src/components/steps/StepInstitutionType.tsx
src/components/steps/StepOnboardingFormData.tsx
src/components/steps/StepSearchParty.tsx
src/locale/it.ts
src/utils/constants.ts
src/views/onboarding/__tests__/Onboarding.test.tsx
src/views/onboarding/components/OnBoardingProductStepDelegates.tsx
src/views/onboarding/components/StepVerifyOnboarding.tsx

feat: Enabled add user entry point flow for specific products + improvements

feat: Enabled add user entry point flow for specific products + improvements

---

src/components/OnboardingStepActions.tsx
src/components/PlatformUserForm.tsx
src/components/RolesInformations.tsx
src/components/steps/StepAddManager.tsx
src/components/steps/StepInstitutionType.tsx
src/components/steps/StepOnboardingFormData.tsx
src/components/steps/StepSearchParty.tsx
src/locale/it.ts
src/utils/constants.ts
src/views/onboarding/Onboarding.tsx
src/views/onboarding/__tests__/Onboarding.test.tsx
src/views/onboarding/components/OnBoardingProductStepDelegates.tsx
src/views/onboarding/components/StepAdditionalInformations.tsx
src/views/onboarding/components/StepVerifyOnboarding.tsx

[SELC-2133] feat: Most speaking translation file keys + added subtitle for steps of add user flow
feat: Enabled add user entry point flow for specific products + improvements
In order to make the add user flow as designed in figma
Tested in DEV environment, the subtitle match with the expected
[SELC-2133]: https://pagopa.atlassian.net/browse/SELC-2133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-2133] feat: Most speaking translation file keys + added subtitle for steps of add user flow

---

src/components/ConfirmRegistrationStep0.tsx
src/components/ConfirmRegistrationStep1.tsx
src/components/FileUploadedPreview.tsx
src/components/FileUploader.tsx
src/locale/it.ts
src/views/uploadContract/cancel/CancelRequestComponent.tsx
src/views/uploadContract/complete/CompleteRequestComponent.tsx
src/views/uploadContract/complete/pages/CompleteRequestSuccessPage.tsx
src/views/uploadContract/outcomePages/AlreadyCompletedRequestPage.tsx
src/views/uploadContract/outcomePages/AlreadyRejectedRequestPage.tsx
src/views/uploadContract/outcomePages/ExpiredRequestPage.tsx
src/views/uploadContract/outcomePages/NotFoundPage.tsx

[SELC-4375] feat: Implemented the Add user complete request flow + error management + refactor
Customized the complete onboarding request flow for add user, disambiguated via the add-user hash parameter + refactor.
Tested in local environment with behaviour tests. The feature work as expected.
[SELC-4375]: https://pagopa.atlassian.net/browse/SELC-4375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-4375] feat: Implemented the Add user complete request flow + error management + refactor

---

src/components/autocomplete/Autocomplete.tsx
src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx
src/components/autocomplete/components/partyAdvancedSearchType/PartyAdvancedSelect.tsx
src/components/steps/StepSearchParty.tsx
src/model/SelfcareParty.ts
src/utils/constants.ts
src/views/onboardingUser/AddUserHeading.tsx
src/views/onboardingUser/OnboardingUser.tsx
src/views/onboardingUser/components/StepSearchOnboardedParty.tsx
src/views/onboardingUser/components/StepSelectProduct.tsx

[SELC-4370] feat: Added SearchOnboardedParty step based on product selected for add user flow
In order to give the possibility to an user that come in this flow from error page in dashboard, after chosen the product, to choose the party for add the new user
[SELC-4370]: https://pagopa.atlassian.net/browse/SELC-4370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-4370] feat: Added SearchOnboardedParty step based on product selected for add user flow

---

src/components/autocomplete/Autocomplete.tsx
src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx
src/views/onboardingUser/components/StepSearchOnboardedParty.tsx

Take first retrieved user flow

---

src/components/autocomplete/Autocomplete.tsx
src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx
src/components/autocomplete/components/asyncAutocomplete/components/AsyncAutocompleteResultsCode.tsx
src/components/autocomplete/components/asyncAutocomplete/components/AsyncAutocompleteSearch.tsx
src/components/autocomplete/components/partyAdvancedSearchType/PartyAdvancedSelect.tsx
src/components/steps/StepAddManager.tsx
src/components/steps/StepSearchParty.tsx
src/lib/__mocks__/mockApiRequests.ts
src/locale/it.ts
src/model/OnboardedParty.ts
src/model/SelfcareParty.ts
src/utils/constants.ts
src/views/onboardingRequest/cancel/__tests__/CancelRequestComponent.test.tsx
src/views/onboardingUser/AddUserHeading.tsx
src/views/onboardingUser/OnboardingUser.tsx
src/views/onboardingUser/__tests__/OnboardingUser.test.tsx
src/views/onboardingUser/components/StepSearchOnboardedParty.tsx
src/views/onboardingUser/components/StepSelectProduct.tsx
types.ts

[SELC-5208] feat: Replaced getProducts with getProductsAdmin + removed product filtering
[SELC-4370] feat: Added SearchOnboardedParty step based on product selected for add user flow
Release in uat environment of the worked feature
All feature are tested in local with behaviour test and unit test and in dev environment. The results are the expected
[SELC-5208]: https://pagopa.atlassian.net/browse/SELC-5208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SELC-4370]: https://pagopa.atlassian.net/browse/SELC-4370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SELC-5208 SELC-4370

---

src/components/__tests__/StepInstitutionType.test.tsx
src/utils/constants.ts
src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx

Removed radioButton "Società a Controllo pubblico" for "Firma con IO", "App IO" and "pagoPa". 
For the proucts "Firma con IO", "App IO" and "pagoPa" the SCPs will not be able to join
Local env

[SELC-5200] feat: Remove radio button "Società a Controllo pubblico" for "Firma con IO", "App IO" and "pagoPa".

---

src/components/steps/StepAddManager.tsx
src/components/steps/StepOnboardingData.tsx
src/locale/it.ts
src/views/AlreadyOnboarded.tsx
src/views/onboardingPremium/OnboardingPremium.tsx
src/views/onboardingPremium/__tests__/OnboardingPremium.test.tsx
src/views/onboardingProduct/OnboardingProduct.tsx
src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx
src/views/onboardingProduct/components/StepVerifyOnboarding.tsx
src/views/onboardingUser/OnboardingUser.tsx

[SELC-5219] feat: Managed all errors on checkManager REST api
Showed a blocking error in order to not allow user to forward when it is not possible to establish with certainty whether the manager has changed or not
Tested in local environment with mocked call. When an error code is returned, the generic error page you expect is shown
[SELC-5219]: https://pagopa.atlassian.net/browse/SELC-5219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5219] feat: Managed all errors on checkManager REST api

---

src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx
src/components/autocomplete/components/asyncAutocomplete/components/AsyncAutocompleteResultsCode.tsx
src/components/autocomplete/components/asyncAutocomplete/components/AsyncAutocompleteSearch.tsx
src/utils/constants.ts
src/views/onboardingPremium/components/SubProductStepVerifyInputs.tsx
src/views/onboardingProduct/OnboardingProduct.tsx
src/views/onboardingUser/OnboardingUser.tsx
src/views/onboardingUser/components/StepSelectProduct.tsx

[SELC-5231] feat: Managed all errors on getProductsAdmin REST api
[SELC-5240] feat: originId filled with subunitCode + added partyLogo and parentDescription in the selected party if present
Release in UAT of the worked features
All features are tested in dev environment ensuring that work as expected
[SELC-5231]: https://pagopa.atlassian.net/browse/SELC-5231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SELC-5240]: https://pagopa.atlassian.net/browse/SELC-5240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SELC-5231 SELC-5240

---

.env.development.local
.env.test.local
src/components/ConfirmRegistrationStep1.tsx
src/components/FileUploadedPreview.tsx
src/components/FileUploader.tsx
src/lib/__mocks__/mockApiRequests.ts
src/locale/it.ts
src/model/RowError.ts
src/utils/constants.ts
src/views/onboardingProduct/OnboardingProduct.tsx
src/views/onboardingProduct/components/StepUploadAggregates.tsx

[SELC-5205] feat: Added checkCsv Rest api + error management
In order to validate the aggregates inserted into csv, grouped by aggregates and errors.
Managed errors with the expected outcome
Tested in dev environment with a "correct" csv and "wrong" csv. In case of "correct" csv uploaded, the continue button is enabled and is possible to submit an onboarding request. In case of "wrong", an error banner is showed and the user can't forward
[SELC-5205]: https://pagopa.atlassian.net/browse/SELC-5205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5205] feat: Added checkCsv Rest api + error management

---

src/views/onboardingProduct/OnboardingProduct.tsx

[SELC-5206] feat: Added isAggregator in the onboarding product submit payload
Added isAggregator info in the onboarding submit payload in order to persist the information if the institution is an aggregator
Tested in development environment, the info is correctly sended when the party is an aggregator. If it is not, the information is not sent
[SELC-5206]: https://pagopa.atlassian.net/browse/SELC-5206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5206] feat: Added isAggregator in the onboarding product submit payload

---

src/views/onboardingProduct/components/StepUploadAggregates.tsx

[SELC-5207] feat: Implemented function to convert json into csv
In order to return a csv starting from a json of errors in case there are incorrect fields in the previously loaded csv
Tested in dev environment, the csv is return correctly with the error data
[SELC-5207]: https://pagopa.atlassian.net/browse/SELC-5207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5207] feat: Implemented function to convert json into csv

---

src/views/onboardingProduct/OnboardingProduct.tsx
src/views/onboardingProduct/components/StepUploadAggregates.tsx

[SELC-5207] feat: Implemented function to convert json into csv
[SELC-5206] feat: Added isAggregator in the onboarding product submit payload
Release in uat environment of the worked feature. With this two last features, the aggregator party that appartain at public administration, can submit an onboarding request by self declaring as aggregator only for App IO product
Tested in dev environment, the aggregator party that appartain at public administration successfully submit an onboarding request. In the payload, are also present the aggregates list and the boolean isAggregator that indicate if the party is an aggregator or not.
[SELC-5207]: https://pagopa.atlassian.net/browse/SELC-5207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

SELC-5207 SELC-5206

---

src/views/onboardingProduct/OnboardingProduct.tsx
src/views/onboardingProduct/components/StepUploadAggregates.tsx

feat: Improvements: Banner disappear when new csv is loaded + ordered the error by rows on csv
Some improvements on user experience
Behaviour tested in local

feat: Improvements: Banner disappear when new csv is loaded + ordered the error by rows on csv

---

src/locale/it.ts

[SELC-4494] feat: Removed unused localized text
Removed unused text
[SELC-4494]: https://pagopa.atlassian.net/browse/SELC-4494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-4494] feat: Removed unused localized text

---

src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx
src/components/autocomplete/components/asyncAutocomplete/components/AsyncAutocompleteResultsCode.tsx
src/components/autocomplete/components/asyncAutocomplete/components/AsyncAutocompleteSearch.tsx
src/components/autocomplete/components/partyAdvancedSearchType/PartyAdvancedSelect.tsx
src/components/steps/StepSearchParty.tsx
src/lib/__mocks__/mockApiRequests.ts
src/locale/it.ts
src/utils/constants.ts
src/views/onboardingProduct/OnboardingProduct.tsx

[SELC-5173] feat: API invocation for private body search via CF
[SELC-4494] feat: Removed unused localized text
Release in UAT of the worked features
Tested in development environment, the behaviour is the expected: no regressions in text localization and the occurrance retrieved from the rest api is correctly managed
[SELC-5173]: https://pagopa.atlassian.net/browse/SELC-5173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SELC-4494]: https://pagopa.atlassian.net/browse/SELC-4494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SELC-5173 SELC-4494

---

src/components/ConfirmRegistrationStep0.tsx
src/components/steps/StepAddManager.tsx
src/locale/it.ts

[SELC-4729] feat: Deleted reference to the attorney in the product and premium onboarding flows
Change request
Tested in local environment, the reference to the attorney in the subtitle is no longer present
[SELC-4729]: https://pagopa.atlassian.net/browse/SELC-4729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-4729] feat: Deleted reference to the attorney in the product and premium onboarding flows

---

.env.development.local
src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/onboardingFormData/__tests__/PersonalAndBillingDataSection.test.tsx
src/components/steps/StepOnboardingFormData.tsx
src/components/steps/StepSearchParty.tsx
src/lib/__mocks__/mockApiRequests.ts
src/model/PDNDBusinessResource.ts
src/setupTests.ts
src/utils/selected2OnboardingData.ts
src/utils/typeGuard-utils.ts
src/utils/validateFields.ts
src/views/onboardingProduct/OnboardingProduct.tsx
src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx
src/views/onboardingProduct/components/StepVerifyOnboarding.tsx

[SELC-5174] feat:  Form enter the organization's data from an infocamere party
Alignment of validation and input fields for the form billing data of a party that comes form infocamere
Checked the onboarding process with a party that comes from infocamere
[SELC-5174]: https://pagopa.atlassian.net/browse/SELC-5174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5174] feat:  Form enter the organization's data from an infocamere party

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/onboardingFormData/__tests__/PersonalAndBillingDataSection.test.tsx
src/locale/it.ts
src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx

[SELC-5272] feat: Field validation Unique code or SDI
Allows to insert in the textfield only: seven characters, uppercase letters, alphanumeric characters
Checked the insertion of characters for the SDI input field
[SELC-5272]: https://pagopa.atlassian.net/browse/SELC-5272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5272] feat: Field validation Unique code or SDI

---

.env.development.local
src/components/ConfirmRegistrationStep0.tsx
src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/onboardingFormData/__tests__/PersonalAndBillingDataSection.test.tsx
src/components/steps/StepAddManager.tsx
src/components/steps/StepOnboardingFormData.tsx
src/components/steps/StepSearchParty.tsx
src/lib/__mocks__/mockApiRequests.ts
src/locale/it.ts
src/model/PDNDBusinessResource.ts
src/setupTests.ts
src/utils/selected2OnboardingData.ts
src/utils/typeGuard-utils.ts
src/views/onboardingProduct/OnboardingProduct.tsx
src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx
src/views/onboardingProduct/components/StepVerifyOnboarding.tsx

[SELC-4729] feat: Deleted reference to the attorney in the product and premium onboarding flows
[SELC-5272] feat: Field validation Unique code or SDI
[SELC-5174] feat: Form enter the organization's data from an infocamere party
Release in UAT of the worked feature
Tested in local environment and dev environment ensuring that the estabilished ac are satisfied
[SELC-4729]: https://pagopa.atlassian.net/browse/SELC-4729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SELC-5272]: https://pagopa.atlassian.net/browse/SELC-5272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SELC-5174]: https://pagopa.atlassian.net/browse/SELC-5174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …

SELC-4729 SELC-5272 SELC-5174

---

src/components/FileUploadedPreview.tsx
src/components/FileUploader.tsx
src/components/RolesInformations.tsx
src/components/steps/StepAddManager.tsx
src/locale/it.ts
src/views/AlreadyOnboarded.tsx
src/views/onboardingProduct/OnboardingProduct.tsx
src/views/onboardingProduct/components/StepAddAdmin.tsx
src/views/onboardingProduct/components/StepUploadAggregates.tsx
src/views/onboardingUser/AddUserHeading.tsx

[SELC-5315] feat: Style and copy changes on aggregates upload
Align client about changes made in mockups
Tested in local ensuring all change request are satisfied
[SELC-5315]: https://pagopa.atlassian.net/browse/SELC-5315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5315] feat: Style and copy changes on aggregates upload

---

src/lib/__mocks__/mockApiRequests.ts
src/locale/it.ts
src/utils/constants.ts
src/views/onboardingProduct/OnboardingProduct.tsx
src/views/onboardingProduct/components/StepUploadAggregates.tsx

[SELC-5316] feat: Custom error csv filename + Added download example aggregates csv link
In order to have a custom and dynamic csv error filename 
Tested in local environment with mocked parties, the error csv name contain the party name and product name as expected
[SELC-5316]: https://pagopa.atlassian.net/browse/SELC-5316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5316] feat: Custom error csv filename + added download example aggregates csv link

---

.devops/deploy-pipelines.yml
.env.development.local
.env.test.local
src/locale/it.ts
src/utils/env.ts
src/views/onboardingProduct/components/StepUploadAggregates.tsx

[SELC-5257] feat: Retrieving the example csv from CDN + custom csv download title
In order to download an example csv that be a guide for the aggregate party to insert aggregates
Tested in dev, the example csv is correctly retrieved from CDN and also downloaded with correct download name and the expected column and row inside
[SELC-5257]: https://pagopa.atlassian.net/browse/SELC-5257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5257] feat: Retrieving the example csv from CDN + custom csv download title

---

.devops/deploy-pipelines.yml
.env.development.local
.env.test.local
src/components/FileUploadedPreview.tsx
src/components/FileUploader.tsx
src/components/RolesInformations.tsx
src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/steps/StepAddManager.tsx
src/lib/__mocks__/mockApiRequests.ts
src/locale/it.ts
src/utils/constants.ts
src/utils/env.ts
src/views/AlreadyOnboarded.tsx
src/views/onboardingPremium/__tests__/OnboardingPremium.test.tsx
src/views/onboardingProduct/OnboardingProduct.tsx
src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx
src/views/onboardingProduct/components/StepAddAdmin.tsx
src/views/onboardingProduct/components/StepUploadAggregates.tsx
src/views/onboardingUser/AddUserHeading.tsx

[SELC-5315] feat: Style and copy changes on aggregates upload
[SELC-5316] feat: Custom error csv filename + added download example aggregates csv link
[SELC-5273] feat: Invocation checkRecipientCode API
[SELC-5257] feat: Retrieving the example csv from CDN + custom csv download title
Release in UAT environment of the worked features
All features are tested in development environment ensuring that implementation work correctly and the business requirements have been satisfied
[SELC-5315]: https://pagopa.atlassian.net/browse/SELC-5315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SELC-5316]: https://pagopa.atlassian.net/browse/SELC-5316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SELC-5273]: …

SELC-5315 SELC-5316 SELC-5273 SELC-5257

---

.env.development.local
.env.test.local
src/views/onboardingProduct/components/StepUploadAggregates.tsx

feat: hide download csv example csv when a csv is uploaded + modified local env variables

feat: hide download csv example csv when a csv is uploaded + modified local env variables

---

src/components/FileUploadedPreview.tsx
src/components/FileUploader.tsx
src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/hooks/useLogin.ts
src/views/onboardingProduct/components/StepUploadAggregates.tsx

feat: some refactor + various improvements + fixed bad behaviour on textfield
Tested in dev environment with some behaviour tests ensuring that the bug is fixed and doing some onboarding request for check the improvements work correctly

feat: some refactor + various improvements + fixed bad behaviour on textfield

---

src/components/onboardingFormData/Heading.tsx
src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/onboardingFormData/__tests__/PersonalAndBillingDataSection.test.tsx
src/components/steps/StepOnboardingFormData.tsx
src/lib/__mocks__/mockApiRequests.ts
src/locale/it.ts
src/utils/validateFields.ts
src/views/onboardingPremium/__tests__/OnboardingPremium.test.tsx
src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx

[SELC-5314] feat: SFE Billing Code field validation
[SELC-5137] feat: Standardize the title of the data page for all prod
Release in uat of the worked features
[SELC-5314]: https://pagopa.atlassian.net/browse/SELC-5314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SELC-5137]: https://pagopa.atlassian.net/browse/SELC-5137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SELC-5314 SELC-5137

---

package.json
src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/onboardingFormData/__tests__/PersonalAndBillingDataSection.test.tsx
src/components/steps/StepOnboardingFormData.tsx
src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx
yarn.lock

[SELC-5303] feat: Upgraded fiscal code regexp + verifyName and verifySurname functions convert accented characters to normal + added unit tests
[SELC-5341] feat: SFE Fiscal Code visible after entering the SDI code
Improved regExps and code to fix a bug that emerged and not encounter any more in the future + SFE Fiscal Code visible after entering the SDI code
Tested with unit test using particular name and surnames with accented characters
[SELC-5303]: https://pagopa.atlassian.net/browse/SELC-5303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SELC-5341]: https://pagopa.atlassian.net/browse/SELC-5341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SELC-5303 SELC-5341

---

src/components/__tests__/StepInstitutionType.test.tsx
src/utils/constants.ts

feat: Enabled psp in uat environment too
In order to enable psp in uat environment too. Production still ruled out for now

feat: Enabled psp in uat environment too

---

src/utils/constants.ts

…'ente ha già aderito"
[SELC-5346] feat: Add link "Aggiunta nuovo amministratore" in page "L'ente ha già aderito"
Add the link "Aggiunta nuovo amministratore" for the product io-sign to enable the flow of add admin
Tested that if a party is already onboarded we are redirect to the AlreadyOnboarded page and the link "Aggiunta nuovo amministratore" it's in page
[SELC-5346]: https://pagopa.atlassian.net/browse/SELC-5346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5346] feat: Add link "Aggiunta nuovo amministratore" in page "L'ente ha già aderito"

---

src/model/OnboardingFormData.ts
src/utils/selected2OnboardingData.ts
src/views/onboardingProduct/components/StepVerifyOnboarding.tsx
src/views/onboardingUser/OnboardingUser.tsx
src/views/onboardingUser/components/StepSearchOnboardedParty.tsx
types.ts

fix: correct parameters

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/steps/StepOnboardingFormData.tsx
src/views/onboardingPremium/__tests__/OnboardingPremium.test.tsx
src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx

…oken tests (#1053)
[SELC]-5383 fix: fixed recipientCode seventh character bug + fixed broken test
In the recipientCode field when the seventh character is typed appears the same error as when the recipientCode value is not associated with the central party and the onboarding flow is blocked.  
Fixed broken tests for OnboardingPremium.test and updated OnboardingProduct.test
Tested that when the seventh character is typed appears the same error as when the recipientCode value is not associated with the central party.  
Unit test.

[SELC]-5383 fix: fixed recipientCode seventh character bug + fixed broken test

---

src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx

…xy/v1/infocamere" for private party
[SELC-5404] feat: added the implementation of API "party-registry-proxy/v1/infocamere" for private party
Added the implementation of the API that goes to research in the infocamere resources for the Private party institution
Tested that the invocation of the API that goes to research a Party in the infocamere resources by his CF returns a successful response
[SELC-5404]: https://pagopa.atlassian.net/browse/SELC-5404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5404] feat: added the implementation of API "party-registry-proxy/v1/infocamere" for private party

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/onboardingFormData/__tests__/PersonalAndBillingDataSection.test.tsx

[SELC-5405] feat: managed form of personal and billing data for private party
Adaptation of the form of personal and billing data section to the private party institutions to be able to continue the onboarding flow
tested that the input fields of the form personal and billing data has the correct behaviour for the rules required and that the user can continue with the correct onboarding flow for the private party institutions.
Added new junit test
[SELC-5405]: https://pagopa.atlassian.net/browse/SELC-5405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5405] feat: managed form of personal and billing data for private party

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx

…neous
[SELC-5349] feat: Distance between label and textfield edge is homogeneous
The labels don't always have uniform spacing with the edge of the textfield, in some case overlap
Tested that the texfield labels have a uniform spacing with the edge of the textfield and that they doesn't overlap.
[SELC-5349]: https://pagopa.atlassian.net/browse/SELC-5349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5349] feat: Distance between label and textfield edge is homogeneous

---

src/utils/constants.ts
src/views/onboardingProduct/components/StepUploadAggregates.tsx

fix download of csv example
When clicking the download example csv the file would not be downloaded on first click.
Tested by deploying brach in dev

[SELC-5468] Fix: download csv example on first click

---

src/views/onboardingProduct/OnboardingProduct.tsx

[[SELC-5478] fix: fixed condition for manually entering billing data
fixed condition for manually entering billing data
Tested that the new condition work as expected

[SELC-5478] fix: fixed condition for manually entering billing data

---

.devops/deploy-pipelines.yml
.env.test.local
src/utils/env.ts
src/views/onboardingProduct/OnboardingProduct.tsx
src/views/onboardingProduct/components/StepUploadAggregates.tsx

added dynamic link of csv example based on the product id
The example of the csv and the fields required changes based on product selected.
Tested in by deploying in dev the branch

[SELC-5468] Feat: download csv example based on the prod id

---

src/model/AggregateInstitution.ts

added optional users inside AggregateInstitution 
For the product prod-pn users for each aggregate might be avaible. Added possibility of optianl param users.

[SELC-5472] Feat: add optional users for aggregates csv

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/onboardingFormData/taxonomy/GeoTaxonomySection.tsx
src/components/onboardingFormData/taxonomy/__tests__/GeoTaxonomySection.test.tsx
src/lib/__mocks__/mockApiRequests.ts

[SELC-5395] feat: Change local geographic area search options
Changed the view of geographic area options
Tested with junit and checked that when the user search a geographic area the options are shown with the new format
[SELC-5395]: https://pagopa.atlassian.net/browse/SELC-5395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5395] feat: Change local geographic area search options

---

src/views/onboardingProduct/OnboardingProduct.tsx
src/views/onboardingUser/OnboardingUser.tsx

[SELC-4567] fix: avoid to send subunitCode if not present
[SELC-5478] fix: fixed condition for manually entering billing data
Environment alignment
checked that the fixes works
[SELC-4567]: https://pagopa.atlassian.net/browse/SELC-4567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SELC-5478]: https://pagopa.atlassian.net/browse/SELC-5478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Merge back prod dev

---

src/components/RolesInformations.tsx

[SELC-5396] feat: Updated link in step add manager
Removed the start icon and added undercover line for the link
tested that the link works and that it looks has expected
[SELC-5396]: https://pagopa.atlassian.net/browse/SELC-5396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SELC-5396 feat: Updated link in step add manager

---

.devops/deploy-pipelines.yml
.env.test.local
src/components/RolesInformations.tsx
src/components/__tests__/StepInstitutionType.test.tsx
src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx
src/components/autocomplete/components/partyAdvancedSearchType/PartyAdvancedSelect.tsx
src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/onboardingFormData/__tests__/PersonalAndBillingDataSection.test.tsx
src/components/onboardingFormData/taxonomy/GeoTaxonomySection.tsx
src/components/onboardingFormData/taxonomy/__tests__/GeoTaxonomySection.test.tsx
src/components/steps/StepSearchParty.tsx
src/lib/__mocks__/mockApiRequests.ts
src/locale/it.ts
src/model/AggregateInstitution.ts
src/utils/constants.ts
src/utils/env.ts
src/utils/selected2OnboardingData.ts
src/views/onboardingProduct/OnboardingProduct.tsx
src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx
src/views/onboardingProduct/components/StepUploadAggregates.tsx
src/views/onboardingUser/OnboardingUser.tsx
types.ts

[SELC-5403] Feat: Add Private Entities radio button on prod-interop
[SELC-5404] feat: added the implementation of API "party-registry-proxy/v1/infocamere" for private party
[SELC-5405] feat: managed form of personal and billing data for private party
[SELC-5349] feat: Distance between label and textfield edge is homogeneous
[SELC-5468] Fix: download csv example on first click
[SELC-5468] Feat: download csv example based on the prod id
[SELC-5472] Feat: add optional users for aggregates csv
[SELC-5395] feat: Change local geographic area search options
Merge back prod dev
[SELC-5496] feat: Updated originId for onboarding flow of SCP and PRV
[SELC-5396] feat: Updated link in step add manager
Release branch release-dev into branch release-uat
Tested in dev enviroment that the onboarding flow …

Release uat

---

src/views/onboardingProduct/components/StepUploadAggregates.tsx

Added product id as parameter
To verify different aggregates csv files based on the product id it was neccesary to add the product id to the qery parms of the api
Tested locally by aiming at dev data and sending an onboarding request for prod-io

[SELC-5500] Feat: Add product id in csv upload verification

---

src/components/autocomplete/components/asyncAutocomplete/components/AsyncAutocompleteResultsCode.tsx
src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx

- [SELC-5595] fix: Bad management in select party
- Clean code and removed the eslint complexity
Resolved a bug that not allow the user to interact and obtain correct responses and experience in add user flow
Tested in DEV environment, the taxCode data arrive correctly to the rest API's
[SELC-5595]: https://pagopa.atlassian.net/browse/SELC-5595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5595] fix: Bad management in select party

---

package.json
src/lib/__mocks__/mockApiRequests.ts
src/locale/it.ts
src/views/onboardingPremium/components/subProductStepPricingPlan/SubProductStepSelectPricingPlan.tsx
src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx
src/views/onboardingUser/__tests__/OnboardingUser.test.tsx
yarn.lock

[SELC-5134] feat: updated labels from "App IO" to "IO" and selfcare-common-frontend version
needed to updated lthe abels from "App IO" to "IO" and selfcare-common-frontend version because there has been some modification to selfcare-common-frontend repo that needed to report also in the frontends where this library it's in use
tested that the labels now are correct and that the library doesn't cause any problems
[SELC-5134]: https://pagopa.atlassian.net/browse/SELC-5134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5134] feat: updated labels from "App IO" to "IO" and selfcare-common-frontend version

---

package.json
yarn.lock

[SELC-5638] feat: updated selfcare-common-frontend version
Updated selfcare-common-frontend version because has been done an updated on that repo
Tested that the new link redirect to the correct accessibility link
[SELC-5638]: https://pagopa.atlassian.net/browse/SELC-5638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5638] feat: updated selfcare-common-frontend version

---

src/components/steps/StepInstitutionType.tsx
src/locale/it.ts
src/utils/constants.ts

[SELC-5703] feat: Added description for RadioButton "Altro"
Added description for RadioButton "Altro"
Tested thast ther is the description under the RadioButton "Altro"
[SELC-5703]: https://pagopa.atlassian.net/browse/SELC-5703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5703] feat: Added description for RadioButton "Altro"

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/utils/validateFields.ts

[SELC-5705] fix: businessRegisterPlace field has to be optional
businessRegisterPlace field has to be an optional field
Tested that the businessRegisterPlace field it's an optional field
[SELC-5705]: https://pagopa.atlassian.net/browse/SELC-5705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5705] fix: businessRegisterPlace field has to be optional

---

src/model/AggregateInstitution.ts
src/utils/constants.ts
src/views/onboardingRequest/download/DownloadCsvFile.tsx

add download aggregates csv file page.
integrate api call to download the page
To allow the download of the csv file from a link in the contract.
Tested locally

[SELC-5632] Feat: add download page for csv file

---

src/views/onboardingRequest/download/DownloadCsvFile.tsx

Fix: add token to api call

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/steps/StepInstitutionType.tsx
src/locale/it.ts
src/model/AggregateInstitution.ts
src/utils/constants.ts
src/utils/validateFields.ts
src/views/onboardingRequest/download/DownloadCsvFile.tsx

[SELC-5632] Feat: add download page for csv file
[SELC-5703] feat: Added description for RadioButton "Altro"
[SELC-5704] fix: fixed the "P.IVA" checkbox when the CF value has not yet been set
[SELC-5705] fix: businessRegisterPlace field has to be optional
Fix: add token to api call
To allow the download of the csv file from a link in the contract.
Added description for RadioButton "Altro".
the "P.IVA" checkbox when the CF value wasn't setted yet, it was already checked.
businessRegisterPlace field has to be an optional field.
Tested thast ther is the description under the RadioButton "Altro".
Tested that when the CF value it's not setted yest, the checkbox it's not checked. When the cf value is entered, the checkbox it's enabled and clickable.
Tested that the businessRegisterPlace field …

Release-uat

---

src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx
src/utils/constants.ts

fix-filter-categories
fix-filter-categories

fix-filter-categories

---

src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx
src/lib/__mocks__/mockApiRequests.ts
src/utils/constants.ts
src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx

Fix filter categories
Fix filter categories

Fix filter categories

---

src/components/autocomplete/Autocomplete.tsx
src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx
src/components/steps/StepOnboardingFormData.tsx
src/components/steps/StepSearchParty.tsx
src/lib/__mocks__/mockApiRequests.ts
src/utils/constants.ts
src/views/onboardingProduct/OnboardingProduct.tsx
src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx

[SELC-5756] fix: Fix category filters for interop and pagopa
The category filters for interop and pagopa are not applied in the search for the entity by tax code, which are instead present in the text search.
Tested wit junit and unit test.
Tested that the category filters for interop and pagopa are applied also in the research entity by tax code.
Tested that for different productId and InstitutionType are applyed the correct category filters.
[SELC-5756]: https://pagopa.atlassian.net/browse/SELC-5756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5756] fix: Fix category filters for interop and pagopa

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/steps/StepOnboardingFormData.tsx
src/utils/validateFields.ts
src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx

[SELC-5713] feat: filed rea, sehare capital and businessRegistrationPlace has to be required for PDND private entities
fileds rea, share capital and businessRegistrationPlace for PDND private entities weren't required and has to be it
Tested that for PDND private entities the fileds rea, share capital and businessRegistrationPlace are required.
Tested with junit test
[SELC-5713]: https://pagopa.atlassian.net/browse/SELC-5713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5713] feat: filed rea, sehare capital and businessRegistrationPlace has to be required for PDND private entities

---

src/utils/constants.ts
src/views/onboardingRequest/download/DownloadCsvFile.tsx

changed the name of the aggregates csv file when downloading 
Hide login button in header
The file should not contain the prod id but the prod title in the name when its download 
Tested in local enviroment

[SELC-5723[ Feat: change name of aggregates csv file

---

src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx

fixed taxCode param
fixed taxCode param passed to the api research with taxCode in the stepSearchParty
Tested that when the user join the add user flow and search for a party in the api it's passed also the taxcode in the params

fixed taxCode param

---

src/model/AggregateInstitution.ts

…ution type
add type of AggregateUserResult
update type AggregateInstitution
To update the type of the response from verifyAggregates api
Tested bu running application and unit tests locally

[SELC-5904] Feat: add type for AggregateUserResult and update AggregateInstitution

---

src/locale/de.ts
src/locale/en.ts
src/locale/fr.ts
src/locale/index.ts
src/locale/sl.ts

[SELC-5993] feat: Managed translations with i18n library
In order to have all the texts in the portal translated into the languages ​​provided. There may be some texts still not translated that will be collected and promptly reported to the agency.
Tested in local environment
[SELC-5993]: https://pagopa.atlassian.net/browse/SELC-5993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5993] feat: Managed translations with i18n library

---

.devops/code-review-pipelines.yml
sonar-project.properties

feat: Setted sonar cloud exclusions for translation file for avoid fake positivity
In order to avoid fake positivity of code duplication triggered by sonarcloud which detected as duplication the fact that the same keys were repeated in the translation files
Tested running sonar cloud, the fake positivity has disappeared

feat: Setted sonar cloud exclusions for translation file for avoid fake positivity

---

src/components/__tests__/StepInstitutionType.test.tsx
src/locale/it.ts
src/utils/constants.ts
types.ts

[SELC-5608] FEAT: Added new institutionType GPU and attached radio button
Added new InstitutionType GPU and attacched radioButton to open a new onboarding flow
- Tested that the new institutionType and the new radioButton is present in the institution type choice for the correct products
- Added junit test for the new institutionType for the correct products
[SELC-5608]: https://pagopa.atlassian.net/browse/SELC-5608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5608] FEAT: Added new institutionType GPU and attached radio button

---

package.json
yarn.lock

[SELC-5946] feat: Resolved vulnerability triggered by nth-check library + moved type definition on devDependencies instead of dependencies
In order to resolve vulnerability triggered by nth-check library
Checked if the audit is fixed by running the command
[SELC-5946]: https://pagopa.atlassian.net/browse/SELC-5946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5946] feat: Resolved vulnerability triggered by nth-check library + moved type definition on devDependencies instead of dependencies

---

src/components/steps/StepAddManager.tsx
src/views/onboardingRequest/complete/CompleteRequest.tsx
src/views/onboardingUser/OnboardingUser.tsx

[SELC-5646] feat: Added mixpanel events into onboarding user flow
In order to monitor within the mixpanel tool, the crucial moments of the user addition flow
Tested in dev environment, the mixpanel event appear when expected
[SELC-5646]: https://pagopa.atlassian.net/browse/SELC-5646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5646] feat: Added mixpanel events into onboarding user flow

---

sonar-project.properties

fixed sonar test duplication check
With this fix, incorrect paths in the client sonar configuration file have been corrected. This will exclude unit tests from code duplication checking.
With this, the sonar cloud check on duplication code passes as expected

fixed sonar test duplication check

---

src/components/ConfirmRegistrationStep0.tsx
src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx
src/views/onboardingProduct/components/StepAdditionalGpuInformations.tsx

Feat: added validation for the abilitation of continue button also for the checkboxes
added validation for the abilitation on the checkboxes of the second form,  updated linked test and made some fix
Tested that the continue button it's enabled only when all the required filed, also checkboxes, have some value

Feat: added validation for the abilitation of continue button also for the checkboxes

---

package.json
yarn.lock

Updated some library version

---

src/components/autocomplete/components/asyncAutocomplete/components/AsyncAutocompleteResultsBusinessName.tsx
src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/steps/StepOnboardingFormData.tsx
src/views/onboardingPremium/OnboardingPremium.tsx
src/views/onboardingPremium/__tests__/OnboardingPremium.test.tsx
src/views/onboardingPremium/components/SubProductStepSelectUserParty.tsx
src/views/onboardingPremium/components/subProductStepPricingPlan/SubProductStepSelectPricingPlan.tsx

[SELC-6280] Feat: Remove page of price selection for the product prod-io-premium
[SELC-6284] Feat: fix pre-populated field "SDI Code" in the onboarding form
[SELC-6310] Feat: In the onboarding request form for the taxCode filed allow to input only 11 charcaters
These features and fixes are needed to update the onboarding flow of prod-io-premium
Tested that the onboarding flow for prod-io-premium works as expected.
Tested with junit test.
[SELC-6280]: https://pagopa.atlassian.net/browse/SELC-6280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SELC-6284]: https://pagopa.atlassian.net/browse/SELC-6284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SELC-6310]: …

[SELC-6280] Feat: Removed page of price selection for the product prod-io-premium

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/lib/__mocks__/mockApiRequests.ts
src/utils/config.json
src/views/onboardingPremium/OnboardingPremium.tsx
src/views/onboardingPremium/__tests__/OnboardingPremium.test.tsx
src/views/onboardingPremium/components/subProductStepPricingPlan/SubProductStepSelectPricingPlan.tsx

Updated config.json file with new pricingPlan field and updated the onboarding flow for prod-io-premium
Removed the logic that retrived the pricingPlan value form the json off "app-io-premium-plans.json" and moved to configuration file "config.json"

Updated config.json file with new pricingPlan field and updated the onboarding flow for prod-io-premium

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/views/onboardingPremium/OnboardingPremium.tsx
src/views/onboardingPremium/components/SubProductStepSelectUserParty.tsx

removed back button from initial step of io-premium.
Fixed taxCode field with an input max length of 11 characters

removed back button from initial step of io-premium

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx

fixed input of taxCode, now allows only numbers

fixed input of taxCode

---

src/index.tsx

update login redirect
update login redirect

feat: update login redirect

---

package.json
src/hooks/useLogin.ts
src/index.tsx
src/utils/unloadEvent-utils.ts
src/views/onboardingPremium/__tests__/OnboardingPremium.test.tsx
src/views/onboardingRequest/cancel/__tests__/CancelRequestComponent.test.tsx
src/views/onboardingRequest/complete/__tests__/CompleteRequestComponent.test.tsx
src/views/onboardingRequest/status/AlreadyCompletedPage.tsx
yarn.lock

Feat: added onSuccess to url login redirect
updated redirect url in the index.tsx file

Feat: added onSuccess to url login redirect

---

src/utils/constants.ts

[SELC-6099] Feat: updated USER_COMPLETE_REGISTRATION path
Swagger Detect Rules and Conflict: /v2/tokens/{onboardingId}/completeOnboardingUsers.
Fix it chenging completeOnboardingUsers in complete-onboarding-users
[SELC-6099]: https://pagopa.atlassian.net/browse/SELC-6099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-6099] Feat: updated USER_COMPLETE_REGISTRATION path

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/steps/StepOnboardingData.tsx
src/components/steps/StepOnboardingFormData.tsx
src/lib/__mocks__/mockApiRequests.ts
src/views/onboardingPremium/OnboardingPremium.tsx
src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx

- Updated dpoSection grid
- Updated vatNumberGroup onChange 
- Updated OnboardingPremium tests
updated onboarding flow for prod-dashboard-psp

Feat: Updated dpoSection grid

---

package.json
yarn.lock

Bumps [@types/lodash] from 4.17.14 to 4.17.15.
Bumps [eslint-config-prettier] from 9.1.0 to 10.0.1.

Feat: bump lib versions

---

src/components/autocomplete/components/asyncAutocomplete/components/AsyncAutocompleteResultsCode.tsx
src/components/steps/StepOnboardingData.tsx
src/components/steps/StepOnboardingFormData.tsx
src/lib/__mocks__/mockApiRequests.ts
src/views/onboardingPremium/OnboardingPremium.tsx
src/views/onboardingPremium/__tests__/OnboardingPremium.test.tsx
src/views/onboardingPremium/components/SubProductStepSubmit.tsx
src/views/onboardingPremium/components/SubProductSubmitFetch.ts
src/views/onboardingProduct/OnboardingProduct.tsx
src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx
types.ts

- updated onboarding flow eith conditions on origin and originId fields
- updated junit tests for OnboardingProduct and OnboardingPremium
updated onboarding flow eith conditions on origin and originId fields

Feat: updated onboarding flow eith conditions on origin and originId fields

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/steps/StepOnboardingFormData.tsx
src/lib/__mocks__/mockApiRequests.ts
src/locale/it.ts
src/utils/constants.ts
src/views/onboardingProduct/OnboardingProduct.tsx
src/views/onboardingRequest/complete/CompleteRequest.tsx

- [SELC-6393] Feat: Add FROM attribute to ONBOARDING_USER_COMPLETED
- SDI code that blocks when entering the 6th character
- the city field in the onboardingForm is editable when it's disabled
- back buttons returns to dashboard in onboarding flow of dashboard-psp
Add FROM attribute to ONBOARDING_USER_COMPLETED for Mixpanel and made some update
[SELC-6393]: https://pagopa.atlassian.net/browse/SELC-6393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-6393] Feat: Add FROM attribute to ONBOARDING_USER_COMPLETED

---

src/views/onboardingProduct/OnboardingProduct.tsx
src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx

retrived originId value in the step of billing data to send the correct originId value (that comes from the regitry)

retrived originId value in the step of billing data

---

package.json
src/reportWebVitals.ts
yarn.lock

bump web-vitals version 1.1.2 -> 4.2.4
- bump web-vitals version 1.1.2 -> 4.2.4
- fixed depracated method ReportHandler

bump web-vitals version 1.1.2 -> 4.2.4

---

src/utils/constants.ts

[SELC-6097] Feat: Swagger Detect Rules and Conflict: recipientCode/verification
recipientCode in the path is not param-case (recipient-code)
[SELC-6097]: https://pagopa.atlassian.net/browse/SELC-6097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-6097] Feat: Swagger Detect Rules and Conflict: recipientCode/verification

---

src/utils/constants.ts

Feat: updated USER_COMPLETE_REGISTRATION path
updated path of USER_COMPLETE_REGISTRATION from completeOnboardingUsers to complete-onboarding-users

Feat: updated USER_COMPLETE_REGISTRATION path

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/onboardingFormData/__tests__/PersonalAndBillingDataSection.test.tsx
src/components/steps/StepOnboardingFormData.tsx
src/locale/it.ts
src/utils/validateFields.ts
src/views/onboardingPremium/OnboardingPremium.tsx
src/views/onboardingPremium/components/SubProductStepSelectUserParty.tsx
src/views/onboardingProduct/OnboardingProduct.tsx
src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx

- upadated pagoPA Insights subproduct title
- fixed legalRegisterNumber error case
- updated origin value for PRV and GPU and updated their tests
- updated geographicTaxonomy error case
Display the correct pagoPA Insights title in onboarding request

Feat: upadated pagoPA Insights subproduct title

---

src/components/onboardingFormData/PersonalAndBillingDataSection.tsx
src/components/steps/StepAddManager.tsx
src/components/steps/StepOnboardingFormData.tsx
src/lib/__mocks__/mockApiRequests.ts
src/locale/it.ts
src/views/onboardingPremium/OnboardingPremium.tsx
src/views/onboardingPremium/components/SubProductStepSelectUserParty.tsx
src/views/onboardingPremium/components/SubProductStepSuccess.tsx
src/views/onboardingPremium/components/SubProductStepUserUnrelated.tsx
src/views/onboardingPremium/components/SubProductStepVerifyInputs.tsx

- updated subProduct "pagoPa insights" labels
- updated pspData values in PersonalAndBillingDataSection if the values arrives as "N/A"
- updated dpoData values in stepOnboardingFormData if the values arrives as "N/A"
To show the correct name of the subProduct

Feat: updated subProduct "pagoPa insights" labels

---

src/views/onboardingPremium/__tests__/OnboardingPremium.test.tsx
src/views/onboardingProduct/OnboardingProduct.tsx
src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx

Updated origin for institutionType PT
The onboarding request for an institution Type PT wasn't sending the "origin" field

[SELC-6692] feat: updated origin for institutionType PT

---

src/utils/test-utils.tsx
src/views/onboardingPremium/__tests__/OnboardingPremium.test.tsx
src/views/onboardingProduct/components/StepAddAdmin.tsx

[SELC-6805] Feat: fixed error on step add administrator
on the page Indicate the Administrator's data, it is possible to add a maximum of 3 Administrators and, once all the mandatory data has been entered, the Continue button is enabled to continue with the membership
[SELC-6805]: https://pagopa.atlassian.net/browse/SELC-6805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-6805] Feat: fixed error on step add administrator

---

.github/workflows/create_release_branch.yml

updated ubuntu version on create-release-branch job
updated ubuntu version on create-release-branch job

updated ubuntu version on create-release-branch job

---

.github/workflows/deploy_cdn.yml

updated ubuntu version for the job promote release
updated ubuntu version for the job promote release

updated ubuntu version for the job promote release

---

e2e/tests/testSCP.spec.ts
e2e/utils/test-utils.ts

[SELC-6841] Feat: Integration Test Fe - SCP
[SELC-6841] Feat: Integration Test Fe - SCP
[SELC-6841]: https://pagopa.atlassian.net/browse/SELC-6841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SELC-6841]: https://pagopa.atlassian.net/browse/SELC-6841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-6841] Feat: Integration Test Fe - SCP

---

src/views/onboardingPremium/OnboardingPremium.tsx
src/views/onboardingPremium/components/SubProductStepNoParties.tsx

Updated back action with the rescue of partyId from the URL
the action of back requires the partyId rescued from the URL

Updated back action with the rescue of partyId from the URL

---

src/views/onboardingPremium/components/SubProductStepNoParties.tsx

updated back action if partyId is null
updated back action if partyId is null

updated back action if partyId is null

---

src/views/onboardingPremium/OnboardingPremium.tsx
src/views/onboardingPremium/components/SubProductStepSelectUserParty.tsx

fix helper link in premium products
fix helper link in premium products

fix helper link in premium products

---

e2e/package.json
e2e/playwright.config.ts
e2e/tests/testGPS.spec.ts
e2e/tests/testPA.spec.ts
e2e/tests/testPSP.spec.ts
e2e/tests/testSCP.spec.ts
e2e/utils/global.setup.ts
e2e/utils/global.teardown.ts
e2e/utils/test-utils.ts
package.json
src/utils/test-utils.tsx

- [SELC-6896] Feat: PSP integration test
- Integrated new login
- added setup and teardown logic
Added global.setup.js and global.teardown.ts to configure the environment for integration testing with playwright. Setup logs in and saves information to a generated file called storageState.json, while teardown cleans and deletes storage. This configuration is needed to configure the environment so that operations such as login are not repeated and to save user information used for testing.
[SELC-6896]: https://pagopa.atlassian.net/browse/SELC-6896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-6896] Feat: PSP integration test

---

e2e/tests/testPT.spec.ts
e2e/utils/test-utils.ts

[SELC-6898] Feat: playwright integration test scenario PT
[SELC-6898]: https://pagopa.atlassian.net/browse/SELC-6898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-6898] Feat: playwright integration test scenario PT

---

src/components/steps/StepAddManager.tsx
src/lib/__mocks__/mockApiRequests.ts
src/utils/constants.ts

[SELC-6982] Feat: Update request of checkManager
Updated the workflow of onboarding user. With this featuring we are going to add the new api searchUser that has in the request the CF of the manager requested for the onboarding. If the api has success, it returns the userId of the manager that will be used for the api checkManager as request parameter.
[SELC-6982]: https://pagopa.atlassian.net/browse/SELC-6982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update check manager

---

e2e/utils/test-utils.ts
package.json
src/__tests__/App.test.tsx
src/components/steps/StepAddManager.tsx
src/index.tsx
src/redux/store.ts
src/utils/constants.ts
src/utils/test-utils.tsx
src/views/onboardingPremium/OnboardingPremium.tsx
src/views/onboardingPremium/__tests__/OnboardingPremium.test.tsx
src/views/onboardingProduct/OnboardingProduct.tsx
src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx
src/views/onboardingUser/OnboardingUser.tsx
src/views/onboardingUser/__tests__/OnboardingUser.test.tsx
yarn.lock

updated stepAddManager, added redux store and updated the tests
updated stepAddManager, added redux store and updated the tests

updated stepAddManager, added redux store and updated the tests

---

e2e/playwright.config.ts
e2e/tests/testGPS.spec.ts
e2e/tests/testPA.spec.ts
e2e/tests/testPSP.spec.ts
e2e/tests/testPT.spec.ts
e2e/tests/testSA.spec.ts
e2e/tests/testSCP.spec.ts
e2e/utils/test-utils.ts

[SELC-6900] Feat:FE Integration Test - Playwright - SA
Added integration test for the SA scenario
[SELC-6900]: https://pagopa.atlassian.net/browse/SELC-6900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-6900] Feat:FE Integration Test - Playwright - SA

---

e2e/tests/testPRV.spec.ts
e2e/utils/global.setup.ts
e2e/utils/test-utils.ts

[SELC-6902] Feat: Integration test FE - Playwright - PRV
[SELC-6902] Feat: Integration test FE - Playwright - PRV
[SELC-6902]: https://pagopa.atlassian.net/browse/SELC-6902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SELC-6902]: https://pagopa.atlassian.net/browse/SELC-6902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-6902] Feat: Integration test FE - Playwright - PRV

---

e2e/tests/testGPU.spec.ts
e2e/utils/test-utils.ts

[SELC-6903] Feat: Integration Test FE - Playwright - GPU
[SELC-6903] Feat: Integration Test FE - Playwright - GPU
[SELC-6903]: https://pagopa.atlassian.net/browse/SELC-6903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SELC-6903]: https://pagopa.atlassian.net/browse/SELC-6903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-6903] Feat: Integration Test FE - Playwright - GPU

---

src/views/onboardingUser/OnboardingUser.tsx

added a variable in the condition of the origin's field
added a variable in the condition of the origin's field

update origin in onboarding user workflow

---

src/components/autocomplete/Autocomplete.tsx
src/components/autocomplete/components/asyncAutocomplete/AsyncAutocompleteContainer.tsx
src/components/autocomplete/components/asyncAutocomplete/components/AsyncAutocompleteSearch.tsx
src/components/steps/StepSearchParty.tsx
src/lib/__mocks__/mockApiRequests.ts
src/utils/config.json
src/views/onboardingProduct/OnboardingProduct.tsx

[Selc-7261] Feat: Add filter to Ateco Whitelist codes
[SELC-7260] Feat: Add banner for ATECO code not present in the whitelist
[SELC-7260]: https://pagopa.atlassian.net/browse/SELC-7260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Selc-7261] Feat: Add filter to Ateco Whitelist codes

---

src/model/OnboardingFormData.ts
src/utils/selected2OnboardingData.ts
src/views/onboardingProduct/OnboardingProduct.tsx

[SELC-7357] Feat: Send the atecoCodes list in the onboarding request
Send the atecoCodes list in the onboarding request
[SELC-7357]: https://pagopa.atlassian.net/browse/SELC-7357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-7357] Feat: Send the atecoCodes list in the onboarding request

---

src/utils/selected2OnboardingData.ts

updated legal form control
updated legal form control to fill the field legalForm only for the product idpay-merchant

updated legal form control

---

src/components/steps/StepSearchParty.tsx
src/locale/en.ts
src/locale/it.ts

updated productName and subtitile for prod-interop in the step StepSearchParty
productName and subtitile were not correct

updated productName and subtitile for prod-interop

---

src/components/onboardingFormData/IbanSection.tsx
src/locale/it.ts
src/model/OnboardingFormData.ts
src/utils/test-utils.tsx
src/utils/validateFields.ts
src/views/onboardingProduct/OnboardingProduct.tsx
src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx

[SELC-7432] Feat: Send account holder and IBAN information in the v2/onboarding request
Send account holder and IBAN information in the v2/onboarding request
[SELC-7432]: https://pagopa.atlassian.net/browse/SELC-7432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-7432] Feat: Send account holder and IBAN information in the v2/onboarding request

---

e2e/playwright.config.ts
e2e/tests/testPRV.spec.ts
e2e/utils/test-utils.ts

[SELC-7579] Feat: Added playwright test scenario related to idpay-merchant onboarding
Added playwright test scenario related to product idpay-merchant
[SELC-7579]: https://pagopa.atlassian.net/browse/SELC-7579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-7579] Feat: Added playwright test scenario related to idpay-merchant onboarding

---

e2e/tests/testSCEC.spec.ts

[SELC-7724] Feat: Add integration test for new institutionType SCEC
Add integration test for new institutionType SCEC
[SELC-7724]: https://pagopa.atlassian.net/browse/SELC-7724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-7724] Feat: Add integration test for new institutionType SCEC
